### ISSUE TITLE
Debug tern.js with Nodeclipse

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/tern.java#106]
Until today, when I develop JavaScript tern plugin, I use Chrome to debug it (with WebBrowser). But some tern plugin like Google Closure Library https://github.com/angelozerr/tern.java/wiki/Tern-&-Closure-support is avaialble only with node.js

Iit should be fantastic to debug tern plugin with Nodeclipse (to benefit with breakpoint).

My idea is to start the tern server with node.js with debug mode. Launch the tern completion inside JSDT editor which calls the node.js tern server and use Nodeclipse editor to debug step by step the tern plugin.

@PaulVI do you think it's possible to do that? It should be very fantastic if we could do that and I think Eclipse could become a very good IDE to develop tern plugin.

I think I must do some improvment for tern.java (like fix the port of the node.js, perhaps add some debug properties when node.js is executed, manage timeout for completion, etc).

Many thank's for your help @PaulVI !

**Comment by angelozerr** [comment]
Done https://github.com/angelozerr/tern.java/wiki/Debugging-Tern.js-on-Node.js

**Comment by paulvi** [comment]
great
