### ISSUE TITLE
UI Preferences for Default Modules

### ISSUE THREAD

**Issue by paulvi** [angelozerr/tern.java#127]
After installing 0.5.0 (all modules) I still don't see Modules preference page

Only 

- Tern
    -Node.js

BTW, Rhino option not installed, but only Node option

**Comment by angelozerr** [comment]
![Default modules](https://github.com/angelozerr/tern.java/wiki/images/EclipseIDE_DefaultModulesPreferences.png)

See https://github.com/angelozerr/tern.java/wiki/New-and-Noteworthy-0.8.0#default-modules
