### ISSUE TITLE
Always use module icon for code suggestions

### ISSUE THREAD

**Issue by paulvi** [angelozerr/tern.java#129]
Because TernIDE is to be used together with JSDT, Nodeclipse https://github.com/Nodeclipse/nodeclipse-1/issues/166 and others, it may be confusing where this suggestion came from

![](https://github.com/angelozerr/tern.java/wiki/images/0.6.0/EcLipseIDE_JSDTAfterTernCompletion.png)

Please always use ternIDE module icon (or derived) for code suggestions.
This way user can know where this suggestion came from

**Comment by angelozerr** [comment]
I close this issue for https://github.com/angelozerr/tern.java/issues/277
