### ISSUE TITLE
[minor] With Nodeclipse 0.17 Tern modules are not shown as selected until re-open

### ISSUE THREAD

**Issue by paulvi** [angelozerr/tern.java#141]
There is some problem with approach of just adding `.tern-project` file https://github.com/Nodeclipse/nodeclipse-1/issues/165

While hints and completions seems to work fine, when I open project Properties and Tern -> Modules
I see none on modules is selected, while  `.tern-project` content is    
`{"libs":["ecma5"],"plugins":{"node":{}},"ide":{}}`

`.project` content is 

```
<?xml version="1.0" encoding="UTF-8"?>
<projectDescription>
	<name>NodeProject017</name>
	<comment></comment>
	<projects>
	</projects>
	<buildSpec>
		<buildCommand>
			<name>com.eclipsesource.jshint.ui.builder</name>
			<arguments>
			</arguments>
		</buildCommand>
	</buildSpec>
	<natures>
		<nature>org.nodeclipse.ui.NodeNature</nature>
		<nature>org.eclipse.wst.jsdt.core.jsNature</nature>
		<nature>tern.eclipse.ide.core.ternnature</nature>
	</natures>
</projectDescription>

```

**Comment by angelozerr** [comment]
@paulvi have you the problem with last version of tern.java? I have improved a lot the obsevation of .tern-project

**Comment by angelozerr** [comment]
@paulvi can I close this issue?
