### ISSUE TITLE
Connect tern.java to an external user installed, user managed, tern server

### ISSUE THREAD

**Issue by MetaMemoryT** [angelozerr/tern.java#142]
This is a very simple solution to issues such as https://github.com/angelozerr/tern.java/issues/43 https://github.com/angelozerr/tern.java/issues/141

### The Problem

Power users and developers are often creating their own tern modules/defs/plugins and hand edit .tern-project files with complex additions that the gui does not support.  For example, the plugin tern-closure supports custom "finder" attributes (look [here](https://github.com/google/tern-closure/blob/master/README.md#-grep) for more information):

```
{
  "plugins": {
    "doc_comment": false,
    "closure": {
      "finder": {
        "name": "grep",
        "dirs": [
          "relevant/project/subdir",
          "/absolute/path/to/library"
        ]
      }
    }
  }
}
```

The gui will always lag behind what the plugins support, so here is a proposal enabling "power users" to work on the bleeding edge (forked tern server, forked plugins, etc) with little hassle and easily debug the tern server.

### The Eclipse Interface

In the eclipse gui, on the project properties, under Tern panel, there would be 2 new options:

use external tern process: \[true / false] (default to false)
port of external tern process: [port number]

And 1 new button:

[Connect to external tern server]

### The New Way to use Tern.java
The new workflow of a "power user"/plugin developer  would be to:

1. Hand edit a .tern-project file in the project root.
2. Ensure all plugins/modules/defs are in the correct paths for the next step.  The power user can retrieve them any way they want, npm install, etc.
3. *Manually* start the tern server with any special args, custom PATH, desired. (type in on the command line):

     ```
    cd eclipse-workspace/<project-root>/
    tern
    ```
4. click the button [Connect to external tern server]  under the eclipse project properties, on tern panel
If the connection failed, an eclipse dialog would pop up "Cannot connect to tern server on port <port>"

### Benefits and Conclusion

This would allow the continuation of development of an "integrated tern" while power users / developers could benefit / test their newly created features before the next tern.java release.

The external tern **would not** be managed by eclipse, it **would not** automatically shutdown, etc.  That is all left up to the developer to manage from the command line, for **each** individual project he wants to have tern support for.

This would make tern much easier to debug, because someone could install tern and then:
```
node-debug tern
```

and use [node-inspector](https://www.npmjs.org/package/node-inspector) to "break on exceptions" when they did some behavior in eclipse that caused tern to create an error.

I found node-inspector much nicer that eclipse v8 debugging, because it has simple "live editing" with no annoying "virtual project files" (what I want is this https://github.com/Nodeclipse/nodeclipse-1/issues/157) and you can set breakpoints in it easier, and the breakpoints persist automatically between sessions, compared to eclipse you have to import/export them every debug launch.

This new system would also fix one other issue,  if the "use external tern process: " is checked, tern.java would never touch the .tern-project file, (because if you are hand editing it, you do not want it minified, or tern.java overwriting it.)  Some projects (like tern itself) contain a hand edited .tern-project, and when imported into tern.java, tern.java automatically overwrites it, creating a git file change you don't want to commit to the main project.

**Comment by paulvi** [comment]
> different editor than eclipse because of JSDT's lack of support for es6

That is https://bugs.eclipse.org/bugs/show_bug.cgi?id=223131

**Comment by paulvi** [comment]
Isn't this done?

**Comment by angelozerr** [comment]
Yes you are right, I close this issue.
