### ISSUE TITLE
Exclude tern script path

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/tern.java#150]
Provide a mean to exclude tern script path (folder, file) to avoid parsing some JS files. For instance if your project has this script folder : 

----------------------------

scripts
    -> lib which contains angular.js
    myscript.js

----------------------------

Here :

 * angular.js must not be parsed by tern (because it exists a tern plugin for angular and angular.js is bif (performance problem)
 * myscript.js must be parsed.

To configure that, use can define tern script paths:

 * script as folder path
 * lib as exclude tern script path to avoid parsing angular.js

Integrates https://github.com/eclipsesource/jshint-eclipse/blob/master/bundles/com.eclipsesource.jshint.ui/src/com/eclipsesource/jshint/ui/internal/preferences/PathPattern.java to support complex path to include/exclude. We will able to support .jshintignore for validation.

**Comment by maxandersen** [comment]
since jsdt already has include/exclude capability - would it not be great if tern.js just used that ?

**Comment by angelozerr** [comment]
As I said you, I cannot have dependencies to JSDT inside tern script path. 

I know the compute of the scope is a very important part of improvment of tern.java, but I must find time to study this topic (I'l very busy with JSON Editor).

**Comment by angelozerr** [comment]
I close this issue, because now it's implemented with https://github.com/angelozerr/tern.java/issues/292
