### ISSUE TITLE
Improve JSDT Install Path -> Tern script path

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/tern.java#168]
Improve JSDT Install Path -> Tern script path

**Comment by paulvi** [comment]
Can "Tern script path" just go into past and only JSDT path be used?

**Comment by angelozerr** [comment]
> Can "Tern script path" just go into past and only JSDT path be used?

tern.java uses their own script paths because I don't want to have dependencies to JSDT.https://github.com/angelozerr/tern.java/tree/master/eclipse/tern.eclipse.ide.jsdt is the plugin which does the glue between JSDT and Tern IDE.

The goal of this issue is to translate correctly tern script path from JSDT Install Path infos.

So you could just use JSDT Install Path instead of useing Tern script path when this issue willl be finished.

**Comment by maxandersen** [comment]
I really think its hurting tern to insist not just using jsdt script path. 

It seems that tern currently does not honor JSDT include path and tern requires '/' to be added to the script path.

**Comment by angelozerr** [comment]
@maxandersen It will be very hard to use JSDT Install Path directly because tern script path belongs to the core (which have none dependencies to Eclipse).

More I would like to support scope for .jshint by using for instance .jshintignore file.
