### ISSUE TITLE
Improve tern file synchronisation

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/tern.java#171]
The PR of @piotrtomiak https://github.com/angelozerr/tern.java/pull/154 has cleaned a lot tern file synchronization, but I think we should improve it because there is 2 problems : 

 * when JS file is moved or deleted, tern server is not updated. See https://github.com/angelozerr/tern.java/issues/157
 * when there are a lot of JS files, UI freeze. The solution is to configure tern script path only for JS files of the app (an dnot the angular, jQuery libraries). See https://github.com/angelozerr/angularjs-eclipse/issues/109#issuecomment-62250057

To fix UI freeze, we must give the capability to stop the post of each JS files to tern server by the user.

Today, when completion, hover, validation, hyperlink is executed on the first, it loop for each tern script path and post JS files to tern server, but I tell me if we could post JS files on the background : 

 * when project is opened, an eclipse job post the whole JS files to tern server.
 * when file is added/removed, moved, a job post the JS file to tern server.

In other words, tern server is every time synchronized before  completion, hover, validation, hyperlink is executed.

So I would like to provide 3 strategies (that user could choose with preferences) to synchronize tern files with tern server : 

 * IDETernFileSynchronizer like today (post JS files when completion, ... is executed the first time). We should improve it to manage move/delete of JS file.
 * use loadEagerly : tern provides "loadEagerly" for the .tern-project http://ternjs.net/doc/manual.html#configuration
which gives the capability to loop for each JS files which follows a pattern on server side directly (the client don't need to post JSON which contains JS files content).

```json
"loadEagerly": ["scripts/**/**.js"]
```
 * manage a job which synchronize js files when project is opened and when file is modified (saved), added, deleted or removed. To support that I would try to investigat eto copy/paste the org.eclipse.wst.sse.core.indexing.AbstractIndexManager inside tern.

@vrubezhny @dgolovin @mickaelistria @maxandersen @pascalleclercq @gamerson @PaulVI @fbricon @piotrtomiak  I think it's an important changes, any comments are welcome. Thank's!

**Comment by piotrtomiak** [comment]
@angelozerr In the first place: happy New Year :) I was planning to start working on the contribution this week, however we still have some stuff to fix before the GA release going out on 15-th of Jan. It looks like I will start work on 19-th of Jan. Sorry for such a delay!

> It's out of the scope of this issue, but I think MyEclipse could be interested with https://github.com/angelozerr/eclipse-wtp-webresources (that you can install with AngularJS Eclipse).

I think so, I stumbled upon this plugin some time ago, but there was no time to put it into the release ;) I hope to include it into next releases.

**Comment by angelozerr** [comment]
> @angelozerr In the first place: happy New Year :) 

Happy New Year!

> It looks like I will start work on 19-th of Jan. Sorry for such a delay!

No pb, it's a very cool news for tern.java. I'm very exciting to see this feature inside tern.java!

>  I think so, I stumbled upon this plugin some time ago, but there was no time to put it into the release ;) I hope to include it into next releases.

Cool!

I think too you could be interested by https://github.com/angelozerr/eclipse-wtp-xml-search

Liferay IDE uses now this project for their XML descriptor (portlet, etc). I could tell you more info, if you need.

**Comment by angelozerr** [comment]
Doen with https://github.com/angelozerr/tern.java/wiki/New-and-Noteworthy-0.9.0#async-tern-completion
