### ISSUE TITLE
acorn vs esprima

### ISSUE THREAD

**Issue by paulvi** [angelozerr/tern.java#210]
I just took a research.

Tern can't be without parser. And it has acorn (just updated to 0.10.0 today)

But for acorn there is alternative esprima http://esprima.org https://github.com/ariya/esprima

And it is proposed to be Eclipse project https://projects.eclipse.org/proposals/esprima
https://projects.eclipse.org/reviews/esprima-creation-review

Have you compared before? Are there other alternatives?

stats:

https://www.npmjs.com/package/acorn
388,575 downloads in the last month

https://www.npmjs.com/package/esprima
2,482,797 downloads in the last month

> Esprima runs on many popular web browsers, as well as other ECMAScript platforms such as Rhino, Nashorn, and Node.js.

while for tern Nashorn is unkown

**Comment by angelozerr** [comment]
> Is there alternative to tern on top of esprima ?

See https://bugs.eclipse.org/bugs/show_bug.cgi?id=432940

> Or esprima itself used for completion and hints ?

See http://esprima.org/demo/autocomplete.html but IMHO it's less powerful than tern and I'm not sure that you cannot develop some plugins for JS fwks (not sure with that).

Can I close this issue?

**Comment by paulvi** [comment]
> Tern does rely on the Acorn parser, which we do not yet use. We should be able to remove this need and have Tern use our shared AST since both Acorn and Esprima create MDN-compliant ASTs.

> 2. I tried to get Tern working nicely with Esprima (the parser base for all of our tools), but there were some rough edges (ie. not working right)

Now Bug 432940 - Investigate using Tern to provide inferred content assist  
is clearer
