### ISSUE TITLE
Rename `node_modules` to `ternjs`

### ISSUE THREAD

**Issue by paulvi** [angelozerr/tern.java#211]
started as https://github.com/angelozerr/tern.java/issues/195#issuecomment-66745816

inside https://github.com/angelozerr/tern.java/tree/master/core/tern.core/ 
rename `node_modules` to `ternjs`

> Today the whole tern plugins are hosted inside https://github.com/angelozerr/tern.java/tree/master/core/tern.core/node_modules

> I have not used npm for that, just copy/paste those tern plugins. So if you think those folder should be redone, don't hesitate to tell me. I think too this https://github.com/angelozerr/tern.java/tree/master/core/tern.core/node_modules should be deleted and move to a new Eclipse project tern.repository which hosts those tern plugins.

OK, for me it is not yet clear 100%

But for Node.js installed modules usually are to come into `node_modules` inside of new `ternjs`

Let's come up with word other than "repository" e.g. "ternjs folder" or "tern copy"

**Comment by angelozerr** [comment]
I would like to move (if it's possible) https://github.com/angelozerr/tern.java/blob/master/core/tern.core/node_modules to a new project call tern.repository. This project will be the default repository, but you can customize your own tern repository.

@paulvi are you OK with that?

**Comment by paulvi** [comment]
sure.
