### ISSUE TITLE
Support for ECMAScript 6

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/tern.java#221]
Support for EcmaScript 6 (only for completion)

**Comment by jabby** [comment]
:+1: for this feature
You can read what is new in this git repository https://github.com/lukehoban/es6features
or of course here https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference

**Comment by angelozerr** [comment]
@jabby first step is to integrates https://github.com/marijnh/tern/pull/475 if tern accept it.

After I think acorn (the JS parser) should be customized to support ES6.

**Comment by jabby** [comment]
@angelozerr Nice PR. I am impress.

**Comment by paulvi** [comment]
:+1:

**Comment by angelozerr** [comment]
![Promise completion](https://github.com/angelozerr/tern.java/wiki/images/EclipseIDE_ECMAScript6PromiseCompletion.png)

See https://github.com/angelozerr/tern.java/wiki/Tern-&-ECMAScript-support#ecmascript-6
