### ISSUE TITLE
Guess parameters of function when completion is applied

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/tern.java#223]
Like Java Editor, provides guess parameters when completion is applied : 

![guessparameters](https://github.com/angelozerr/tern.java/wiki/images/EclipseIDE_GuessTypesCompletionApplied.png)

To support that, integrates tern plugin https://github.com/angelozerr/tern-guess-types

See https://github.com/angelozerr/tern.java/wiki/New-and-Noteworthy-0.8.0#guess-types

**Comment by angelozerr** [comment]
See https://github.com/angelozerr/tern.java/wiki/New-and-Noteworthy-0.8.0#guess-types

**Comment by angelozerr** [comment]
@vrubezhny @dgolovin @mickaelistria @maxandersen @pascalleclercq @gamerson @PaulVI @fbricon @piotrtomiak do you think this tern plugin must be activated by default (like today ECMAScript 5)?

**Comment by gamerson** [comment]
+1

On Mon, Jan 19, 2015 at 6:23 PM, Angelo <notifications@github.com> wrote:

> @vrubezhny <https://github.com/vrubezhny> @dgolovin
> <https://github.com/dgolovin> @mickaelistria
> <https://github.com/mickaelistria> @maxandersen
> <https://github.com/maxandersen> @pascalleclercq
> <https://github.com/pascalleclercq> @gamerson
> <https://github.com/gamerson> @PaulVI <https://github.com/PaulVI> @fbricon
> <https://github.com/fbricon> @piotrtomiak <https://github.com/piotrtomiak>
> do you think this tern plugin must be activated by default (like today
> ECMAScript 5)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angelozerr/tern.java/issues/223#issuecomment-70472333>
> .
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by jabby** [comment]
:+1:

**Comment by piotrtomiak** [comment]
+1

**Comment by maxandersen** [comment]
this looks like something that is relevant for any javascript code or library so +1

**Comment by maxandersen** [comment]
maybe it should just be part of ecmascript plugin instead of separate ?

**Comment by angelozerr** [comment]
Ok glad this plugin seems to please you :) I will activate it by default but it will work only when tern project is creating the first time.

> maybe it should just be part of ecmascript plugin instead of separate ?

I cannot do that, because ecma5.json is a part of tern.

**Comment by vrubezhny** [comment]
It might be too late (but github is not fastest in notifications), but I like this feature! So: +1!

**Comment by angelozerr** [comment]
> It might be too late (but github is not fastest in notifications), but I like this feature! So: +1!

No problem @vrubezhny This feature is activated by default (it works only when project is converted to a tern project or with ternNatureAdapter extension point).
