### ISSUE TITLE
Add ability to configure default tern project modules with Extension Point

### ISSUE THREAD

**Issue by gamerson** [angelozerr/tern.java#228]
Right now the only way to configure modules is using defaultModules, but I noticed that the schema has a way to provide a ITernProjectConfigurator but it is never read.  

Could we add support for that (reading the class attribute for the module) so that we can configure the version based on the user's project config?

**Comment by angelozerr** [comment]
@gamerson I will implement this feature ASAP.

**Comment by angelozerr** [comment]
See https://github.com/angelozerr/tern.java/wiki/Tern-IDE-Extension#idefaultternmodulesprovider

**Comment by angelozerr** [comment]
@gamerson See my PR https://github.com/liferay/liferay-ide/pull/53 for Liferay IDE. Tell me if it works for you and if it works please close this issue. Thanks!

**Comment by gamerson** [comment]
This is working good! thanks for the PR

On Wed, Jan 28, 2015 at 1:09 PM, Angelo <notifications@github.com> wrote:

> Closed #228 <https://github.com/angelozerr/tern.java/issues/228>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angelozerr/tern.java/issues/228#event-225857838>.
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by angelozerr** [comment]
That's cool!
