### ISSUE TITLE
[Dev] Include java auto-formatter preferences in Tern plugin projects

### ISSUE THREAD

**Issue by piotrtomiak** [angelozerr/tern.java#230]
In my environment I do not have auto-formatting of java files enabled, as it doesn't allow me to format the code the way I like it ;) However, it seems that @angelozerr has auto-formatter turned on and in some commits there are a lot of formatting changes happening on particular files (e.g. commit 2165bfddd007f3142f2c2b18de3b1f491bb007b4, file ITernFileSynchronizer), which makes it harder to understand what is changing. Angelo, as I am now working on Issue #171, I propose that you include auto-formatting preferences with all Tern and Angular projects, so that any contributions conform to your settings.

**Comment by angelozerr** [comment]
@piotrtomiak  I'm using default Java Formatter `Eclipse [build-in]`.

**Comment by angelozerr** [comment]
> Angelo, as I am now working on Issue #171

That's very cool!

**Comment by angelozerr** [comment]
@piotrtomiak I would like to commit some improvment for https://github.com/angelozerr/tern.java/issues/223 

I have done several refactoring, can I do or do you prefer I'm waiting for your PR?

**Comment by piotrtomiak** [comment]
Sure, go on, it will take me some time to finish, and I will adjust to your changes.

> I'm using default Java Formatter Eclipse [build-in].

Ok, anywyas, it would be cool if you set up projects for auto-formatting exactly the way you want them to be :)
