### ISSUE TITLE
Release 0.8.0 in January

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/tern.java#231]
@piotrtomiak do you think it's possible to create your PR next week? I would like to create a release for this month. If it's not possible for you, your feature will be integrated for 0.9.0.

@pascalleclercq is it possible for you to create the 0.8.0 release next week (once we will have answer of @piotrtomiak)?

Many thanks for your help!

**Comment by piotrtomiak** [comment]
@angelozerr yes, I am almost finished with it. However, it will require a bit of testing on your side as well, as I am not that familiar with all AngularJS features.

**Comment by angelozerr** [comment]
@piotrtomiak thanks for your answer. Ok I will integrate your cool feature in 0.9.0.

@pascalleclercq go go go for the release!

**Comment by angelozerr** [comment]
Thanks @pascalleclercq !

**Comment by paulvi** [comment]
Just noticed 0.8.0 release.
Will update my links and announce later.

**Comment by paulvi** [comment]
https://github.com/angelozerr/tern.java/wiki/New-and-Noteworthy-0.8.0

**Comment by angelozerr** [comment]
@paulvi pay attention, eclipse market place doesn't work. See https://github.com/angelozerr/tern.java/pull/215#issuecomment-71798437

I don't know how to fix that?

**Comment by angelozerr** [comment]
for your info @paulvi "Completion String" is a tern modules, it is on the side bar inside tern modules.

**Comment by paulvi** [comment]
> for your info @paulvi "Completion String" is a tern modules, it is on the side bar inside tern modules.

yes, I added it first on side bar, than had to remove.

**Comment by paulvi** [comment]
@angelozerr Should not Completion Guess be inside "Tern modules" not "Tern completion" ?

https://github.com/angelozerr/tern.java/wiki/New-and-Noteworthy-0.8.0#completion-guess

**Comment by angelozerr** [comment]
Because "Completion Guess"  is a tern plugin
