### ISSUE TITLE
Question: JSDoc DocBlock comments or Block Tags autocompleter

### ISSUE THREAD

**Issue by extdevelopment** [angelozerr/tern.java#233]
I would like to ask it is possible to in Tern - Eclipse IDE set DocBlock  like
https://github.com/spadgos/sublime-jsdocs
![](https://camo.githubusercontent.com/415148aecc6dac2e5ebb12b7f7584f4a8744eca4/687474703a2f2f73706164676f732e6769746875622e696f2f7375626c696d652d6a73646f63732f696d616765732f66756e6374696f6e2d74656d706c6174652e676966)
or any autocompleter JSDoc Block Tags  solution?
thx

**Comment by angelozerr** [comment]
It's an intersting feature, yes. To implement that we must study : 

 * in Eclipse side, how to detect that comments must be generated (after /** + Enter comments must be generated)
 * in Tern side how to retrieve function parameters. To do that we must improve https://github.com/angelozerr/tern.java/wiki/Tern-&-Completion-Guess-support

**Comment by angelozerr** [comment]
Note that JSDT does a little that. It generates : 

```javascript
/**
 * 
 * @param baz
 * @param quux
 */
function foobar(baz, quux) {}
```

**Comment by extdevelopment** [comment]
Can i use mixed Tern and JSDT, mainly Tern and little bit JSDT only DocBlock generation at present somehow?
I failed to set this.
thx

**Comment by angelozerr** [comment]
> Can i use mixed Tern and JSDT

Yes, tern compeltion is an extension of JSDT compeltion.

To use JSDT DocBlock  generation, you must configure your project to JavaScript Project.

**Comment by extdevelopment** [comment]
Thank you for the information.
`<nature>org.eclipse.wst.jsdt.core.jsNature</nature>` was in the project, and project rebuild helped. Now works.

`@deprecated` can autocompleter
`@description` can't autocompleter

Anonymous function declaration do not like, but prototype worked.

<pre>
/**
 * 
 */
var Person = function(firstName, lastName) {
	  this.firstName = firstName;
	  this.lastName = lastName;
	};


/**
 * 
 * @returns {String}
 */
Person.prototype.getName = function() { 
	return this.firstName + ' ' + this.lastName; 
};

/**
 * 
 * @param firstName
 * @param lastName
 * @returns {String}
 */
Person.prototype.getName2 = function(firstName, lastName) { 
	return firstName + ' ' + lastName; 
};
</pre>

Thanks for the help.

**Comment by angelozerr** [comment]
Please post your question to JSDT Project.

As JSDT supports this feature, I think I will not implement it. I close the issue.
