### ISSUE TITLE
Undefined JavaScript/Css file

### ISSUE THREAD

**Issue by Ghassan-Fadila** [angelozerr/tern.java#236]
Hello,

When trying to load a file without specify the protocol the editor shows this error (in the title):

for example:

```html
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.20/angular.min.js"></script>
```

or 

```html
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
```

adding https or http solve this, but is should work without it,

Thanks a lot,
Ghassan

**Comment by angelozerr** [comment]
Please create this issue at https://github.com/angelozerr/eclipse-wtp-webresources/issues
