### ISSUE TITLE
Stop JS files post

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/tern.java#237]
When you have a lot of JS files and you execute completion, it post JS files to tern server with asynch mode (that's very cool), but if you try to stop it (you can do that if you hava activated tern console), it continues to post JS files). It should be cool if we could stop the posting of JS files.

@piotrtomiak I know you have done something for that but it seems that it doesn't work with my sample? I will study that when I will have time.

**Comment by piotrtomiak** [comment]
Have you tried stopping the job in progress view ?

**Comment by angelozerr** [comment]
Yes I have tried. I will study more my case.

But it should be cool too if we can stop this job when tern server is disposed (when you ciick on stop button of the Console View when you have activated tern console).

**Comment by angelozerr** [comment]
@piotrtomiak  your PR https://github.com/angelozerr/tern.java/pull/241 fixes this issue. Thanks!
