### ISSUE TITLE
jquery code assist

### ISSUE THREAD

**Issue by Ghassan-Fadila** [angelozerr/tern.java#238]
Hello,

when I trying to use jquery 'on' with data param:

$('selector').on('click', {key: 'val'}, function() {});

I got an error:
Invalid argument at 2: cannot convert from Object.prototype to Function.prototype

this does not happen when use 'one'

**Comment by angelozerr** [comment]
```
Invalid argument at 2: cannot convert from Object.prototype to Function.prototype
```

this messages comes from the tern-lint plugin. So I suppose you have checked lint tern module. 

For lint probleme, please create issues at https://github.com/angelozerr/tern-lint/issues
