### ISSUE TITLE
Display "Completion proposals took to long to calculate. Try again in a few seconds..." on the top

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/tern.java#239]
When timeout is doen for completion, a message Completion proposals took to long to calculate. Try again in a few seconds..." is displayed. 

If the project have JSDT Nature, this messages is displayed after JSDT completion item (Document, etc). I think it's better to display this message on the top of the completion..

**Comment by angelozerr** [comment]
@piotrtomiak hope you will like it.

**Comment by piotrtomiak** [comment]
Sure, I do :)
