### ISSUE TITLE
Infinite loop when "Synchronizing script resources" when errors occured

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/tern.java#240]
@piotrtomiak I have a problem when tern serevr loading fails. "Synchronizing script resources" is redone everytime. The server start, it starts, stop, etc

To have this problem use last version of tern.java, select just Dojo Toolkit 1.6 (there is a bug that I must discover)  tern module and try to open completion.

 Dojo Toolkit 1.6 module fails : 

```
if (base.isShell) {
            ^
TypeError: Cannot read property 'isShell' of null
    at passTwo (D:\_Projects\git\tern.java\core\ternjs\node_modules\tern\lib\def.js:351:13)
```

and this erros appears everytime because "Synchronizing script resources"  cannot stop.

**Comment by piotrtomiak** [comment]
I this could be related to enhancement to Issue #237 . It looks like the update job should be tied to the server. I have delays and I still wasn't able to go back to Tern and integrate it with MyEclipse :/ I will try to resolve both issues today.

**Comment by angelozerr** [comment]
Thanks @piotrtomiak for your help.

I have started to introduce your cool feature at https://github.com/angelozerr/tern.java/wiki/New-and-Noteworthy-0.9.0#asynch-tern-completion

Don't hesitate to update it to improve it.

**Comment by piotrtomiak** [comment]
I am almost done with the fix, but need to finish for today. Will make PR tomorrow morning.

**Comment by angelozerr** [comment]
@piotrtomiak  your PR https://github.com/angelozerr/tern.java/pull/241 fixes this issue. Thanks!

**Comment by piotrtomiak** [comment]
@angelozerr did you manage to fix the issue with Dojo 1.6 ? Do you have an issue created for it?

**Comment by angelozerr** [comment]
@piotrtomiak yes I have created an issue at https://github.com/marijnh/tern/issues/491

**Comment by piotrtomiak** [comment]
thanks for the info. For now, I have reverted your commit on our branch for MyEclipse and both issues are gone :)

**Comment by angelozerr** [comment]
>  I have reverted your commit on our branch for MyEclipse and both issues are gone :)

I have revert ternjs too. You can synchronize with tern.java. You can start to play with Linter like JSHint, ESLint etc https://github.com/angelozerr/tern.java/wiki/Tern-Linter

I'm developping UI for JSHint (it's just the UI). Don't hesitate to give me some feedback. Thanks

**Comment by piotrtomiak** [comment]
Cool. I don't think we will have time to integrate your liniting support now. We can't expect users to use the Tern Builder, since all validation is done through WST validation framework. I guess I will start working on integration in 2-3 weeks only. So, no feedback for now ;)

**Comment by angelozerr** [comment]
I'm developping the lhe linting support, so there are a lot of thing to do again like customize linter with UI preferences (I'm working on this toopic) and improve tern script path to exclude JS files and support for instance https://github.com/jshint/jshint/blob/master/examples/.jshintignore

I hope in 2-3 weeks, I will provide a basic UI to customize JSHint.

**Comment by angelozerr** [comment]
> We can't expect users to use the Tern Builder, since all validation is done through WST validation framework. I guess I will start working on integration in 2-3 weeks only.

You mean that TernBuilder is bad idea. It should be better to implement Tern linter with WST Validation. Is that? If you think that WS Validation is better than builder, could you just explain why? After that I will investigate how to replace TernBuilder with a WST Validation.

**Comment by piotrtomiak** [comment]
Well, I am not saying it's bad from technical point of view. It's kind of the same. But we want our users to have smooth migration from previous versions of MyEclipse and adding a new builder to the project is not helping ;) Additionally, WTP Validators have a nice pref page to disable and configure validators to which our users are accustomed and we have custom validation exclusion mechanism based on WTP Validation framework. So basically, we need to have validation mechanism based on WTP validators.

**Comment by angelozerr** [comment]
> So basically, we need to have validation mechanism based on WTP validators.

Ok! I will try to migrate tern builder to WTP Validator.

**Comment by piotrtomiak** [comment]
Cool!
