### ISSUE TITLE
Validate JavaScript files with JSHint

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/tern.java#242]
Validate JavaScript files with JSHint by using https://github.com/angelozerr/tern-jshint

**Comment by angelozerr** [comment]
See https://github.com/angelozerr/tern.java/wiki/Tern-Linter-JSHint Now I must create a new plugin which will provide UI preferences to customize JSHInt

**Comment by angelozerr** [comment]
@vrubezhny @dgolovin @gamerson @PaulVI @piotrtomiak pay attention if you are using id of properties/preferences page, I have changed it.

For instance https://github.com/angelozerr/tern.java/commit/88c022400c0795a448b4ffd079b28d0e06e8d4c0#diff-1cb7c6096f9a37ccb697d0c3eb024e10R148

**Comment by jabby** [comment]
@angelozerr When you said that you will create a basic UI to customize JSHint, did you mean that configuration will be stored in workspace preferences or in project preferences ?

I think that read .jshintrc file to customize jshint will be a great feature. In fact when I use tern.java, it's for projects which are build with yeoman. In generators there is commonly .jshintrc files which contain all configuration. It will be painful if users, like me, need to create the same configuration in tern.java.

**Comment by angelozerr** [comment]
@jabby my idea is to store JSHint configuration :

 * inside .tern-project
 * inside a given .jshintrc

Here a screenshot about my idea: 

![jshintconfig](https://cloud.githubusercontent.com/assets/1932211/6190734/53377bde-b3a4-11e4-94ff-a4cac722aaa3.png)

I would like to provide a first version with this feature. After we could improve it like Jetbrains https://www.jetbrains.com/idea/help/jshint.html

Don't hesitate to tell me feedback about the UI (attach screenshot) if you don't like my proposition. Thanks

**Comment by jabby** [comment]
@angelozerr It's a good idea to let choice at user. I will try this feature during the next week.

**Comment by angelozerr** [comment]
>  I will try this feature during the next week.

It's just an ideao of UI. It's not implemented.

**Comment by jabby** [comment]
Ok. So the UI in your previous comment is good for me. Tell me when the UI will be available.

**Comment by angelozerr** [comment]
@jabby you can install 0.9.0 SNAPSHOT of AngularJS Eclipse. It provides now the capability to validate  with a WTP Validator your JS with JSHint and you can use a `.jshintrc` to customize it : 

![JSHint config file](https://github.com/angelozerr/tern.java/wiki/images/EclipseIDE_JSHintPreferencesConfigFile.png)

Please read https://github.com/angelozerr/tern.java/wiki/Tern-Linter  and https://github.com/angelozerr/tern.java/wiki/Tern-Linter-JSHint#configfile for more information.

**Comment by paulvi** [comment]
wow, screenshots look terrific :+1:

**Comment by paulvi** [comment]
Will `.tern-project` way to configure validation be tool independent?
That is the same config when using JSHint, ESLint? [naive?]

**Comment by angelozerr** [comment]
> wow, screenshots look terrific :+1: 

Glad it pleases you:)

> Will .tern-project way to configure validation be tool independent?

As tern linter can be used with other editor like Emacs, Vim, Sublime, linter config (or using a config file) are stored in this file. I have updated the wiki : 

 * see https://github.com/angelozerr/tern.java/wiki/Tern-Linter-JSHint#config when none .jshintrc is used.
 * see https://github.com/angelozerr/tern.java/wiki/Tern-Linter-JSHint#configFile when you wish to use a .jshintrc file.

> That is the same config when using JSHint, ESLint? [naive?]

Yes it will the same mean, but I had no time to do it for the moment. Only JSHint is configurable for the moment. ESLint, Lint, JSCS is available but not configurable.

**Comment by angelozerr** [comment]
@jabby @piotrtomiak could you give me some feedback about the JSHint linter please when you have will have time. I would liek to do a release soon. Thanks!

**Comment by angelozerr** [comment]
I close this issue since integration of JSHInt was done.
