### ISSUE TITLE
Connection to nodejs refused 

### ISSUE THREAD

**Issue by lxbzmy** [angelozerr/tern.java#243]
On Mac pro 10.10 tern cannot connect to nodejs.

Env:
- Mac Pro 10.10 
- Node 0.10.35 
- Tern 0.8.0

nodejs start correct,listen on port 52589
But tern report connection refused on http://localhost:52589(and there is no proxy config used).
This use curl verbose:
```shell
localhost:plugins lxb$ curl -v http://localhost:52989/
* Hostname was NOT found in DNS cache
*   Trying ::1...
* connect to ::1 port 52989 failed: Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 52989 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.37.1
> Host: localhost:52989
> Accept: */*
> 
< HTTP/1.1 400 Bad Request
< content-type: text/plain
< Date: Thu, 05 Feb 2015 09:56:54 GMT
< Connection: keep-alive
< Transfer-Encoding: chunked
< 
* Connection #0 to host localhost left intact
Missing query document
```

When I change hostname string from `localhost` to `127.0.0.1` in `server/nodejs/NodejsTernServer.java`.
This problem solved.

So,am I missing something?

**Comment by angelozerr** [comment]
> So,am I missing something?

In my case I use Windows and it works, but it seems that they are a problem with Mac -(

The officicial integration with emacs https://github.com/marijnh/tern/blob/master/emacs/tern.el#L562 uses too `127.0.0.1`

So perhaps we should change `locahost` to `127.0.0.1`? 

@vrubezhny @dgolovin @mickaelistria @maxandersen @pascalleclercq @gamerson @PaulVI @fbricon @piotrtomiak it's an important change, are you OK to change `locahost` to `127.0.0.1`?

**Comment by maxandersen** [comment]
+1 this could explain why I have had issues with our integration lately.

**Comment by vrubezhny** [comment]
I don't have a Mac to test it, but I don't see a reason why not to use an IP address instead of 'localhost' synonym. While 127.0.0.1 points to local computer, any synonym can be configured to any address as well as it can be not configured at all. So, +1 for this change.

**Comment by lxbzmy** [comment]
May this is nodejs issue.
Because, I test get http://localhost:80 which apache running ,It  works well,
while nodejs refused connection use "localhost" . when bind use '0.0.0.0' ,there is no problem.

**Comment by angelozerr** [comment]
> May this is nodejs issue.

I don't know but the goal is that ternjs works after tern.java install. If the of change `locahost` to `127.0.0.1` works for any OS, I will change that.

@maxandersen and @vrubezhny are OK for this change. I'm waiting for answer of @gamerson @PaulVI @piotrtomiak which integrates too tern.java

**Comment by piotrtomiak** [comment]
I think it is fine. I remember some troubles with Tomcat port detection on 8080 on Mac, but don't recall details. I think we were using localhost:8080 and it couldn't connect.

**Comment by angelozerr** [comment]
> I think it is fine. 

You mean that you are OK to change `locahost` to `127.0.0.1` ?

**Comment by gamerson** [comment]
+1

On Thu, Feb 5, 2015 at 11:23 PM, Angelo <notifications@github.com> wrote:

> I think it is fine.
>
> You mean that you are OK to change locahost to 127.0.0.1 ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angelozerr/tern.java/issues/243#issuecomment-73063926>
> .
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by piotrtomiak** [comment]
> You mean that you are OK to change locahost to 127.0.0.1 ?

yes, exactly :)

**Comment by angelozerr** [comment]
Thanks everybody for your answer! Now tern.java uses 127.0.0.1
