### ISSUE TITLE
typo: to long; Calculating completion proposal took too long

### ISSUE THREAD

**Issue by paulvi** [angelozerr/tern.java#247]
in https://github.com/angelozerr/tern.java/wiki/New-and-Noteworthy-0.9.0

there is typo

![](https://github.com/angelozerr/tern.java/wiki/images/EclipseIDE_TernSynchFileCompletionToLongToCalculate.png)

should be "too long"

**Comment by paulvi** [comment]
Also I think "Calculating completion proposal took too long." would be better English,  

and similar to string shown in Progress View

**Comment by angelozerr** [comment]
> Also I think "Calculating completion proposal took too long." would be better English,

@piotrtomiak what do you think about that?

**Comment by piotrtomiak** [comment]
Agreed. Though I would make "proposal" plural, so the message is: "Calculating completion proposals took too long."

**Comment by angelozerr** [comment]
Ok I have fixed the typo.

@piotrtomiak do you know if it's possible 

 * to add the filename which is processing in the job message? 
 * to add file number to process (ex : 2/1000 files processed)?

**Comment by piotrtomiak** [comment]
It is sending 20 files per request, so it will be hard to display file names, however I think you could display number of files.
