### ISSUE TITLE
IllegalArgumentException occurs in RefreshTernProjectJob

### ISSUE THREAD

**Issue by vrubezhny** [angelozerr/tern.java#251]
When opening a projects JSP/HSML page in editor while a project is being built, an error dialog appears and error message is written into the Error Log:

!ENTRY org.eclipse.core.jobs 4 2 2015-02-13 05:24:36.400
!MESSAGE An internal error occurred during: "Refresh tern project job".
!STACK 0
java.lang.IllegalArgumentException: Attempted to beginRule: R/, does not match outer scope rule: P/HelloCordova
	at org.eclipse.core.runtime.Assert.isLegal(Assert.java:63)
	at org.eclipse.core.internal.jobs.ThreadJob.illegalPush(ThreadJob.java:134)
	at org.eclipse.core.internal.jobs.ThreadJob.push(ThreadJob.java:333)
	at org.eclipse.core.internal.jobs.ImplicitJobs.begin(ImplicitJobs.java:85)
	at org.eclipse.core.internal.jobs.JobManager.beginRule(JobManager.java:306)
	at org.eclipse.core.internal.resources.WorkManager.checkIn(WorkManager.java:118)
	at org.eclipse.core.internal.resources.Workspace.prepareOperation(Workspace.java:2251)
	at org.eclipse.core.internal.resources.Project.setDescription(Project.java:1347)
	at org.eclipse.core.internal.resources.Project.setDescription(Project.java:1401)
	at tern.eclipse.ide.internal.core.builder.TernBuilder.addTernBuilder(TernBuilder.java:236)
	at tern.eclipse.ide.internal.core.resources.IDETernProject.doLoad(IDETernProject.java:200)
	at tern.resources.TernProject.load(TernProject.java:407)
	at tern.eclipse.ide.internal.core.resources.RefreshTernProjectJob.runInWorkspace(RefreshTernProjectJob.java:49)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

See for reference: https://issues.jboss.org/browse/JBIDE-19119 - Tern error when opening a jsp file.

**Comment by vrubezhny** [comment]
@angelozerr, if this fix is OK, could you merge it, if possible, into 0.7.x and 0.8.x streams too?

**Comment by angelozerr** [comment]
> if this fix is OK, could you merge it, if possible, into 0.7.x and 0.8.x streams too?

I'm sorry I don't know how to do that -(. We have just a master branch and tags like
https://github.com/angelozerr/tern.java/blob/tern.java-0.7.0/eclipse/tern.eclipse.ide.core/src/tern/eclipse/ide/internal/core/resources/IDETernFileSynchronizer.java

But tags cannot be change?

**Comment by piotrtomiak** [comment]
@angelozerr - you would have to create a branch from tag, than cherry-pick the commit and fire off a new build on that branch and than create a new tag like 0.8.1 ;)

**Comment by angelozerr** [comment]
@piotrtomiak thanks for your info! I will do that when I will have time.

**Comment by vrubezhny** [comment]
@angelozerr, yes, @piotrtomiak is correct - you have to make a branch based on the latest commit of 0.8.0 then pick up the required commit into it, increase the versions, set up the build environment (to use that branch instead of master) and that's it.

**Comment by angelozerr** [comment]
Ok @vrubezhny thanks.

@pascalleclercq do you think you could have time to do that?

**Comment by pascalleclercq** [comment]
Hi,

@angelozerr will do It ASAP which means before the end of next week (hopefully earlier..).

@vrubezhny do you expect a new release (0.7.1 and 0.8.1) of tern only or do you expect a corresponding release of angularjs-eclipse in the mean time ?

thx

**Comment by vrubezhny** [comment]
@pascalleclercq yes, probably... I mean at least we should have been guaranteed that Angularjs-eclipse will be able to work with Tern.java's 0.7.1 and 0.8.1 builds.

**Comment by angelozerr** [comment]
@pascalleclercq thanks for your help!

@vrubezhny we will do those 2 releases this time. But we wish to avoid doing that for next releases, because it takes a time (and as we develop tern.java in our spare time, we have not a lot of time). It should be cool if we will able to find another solution next time. Hope you will understand.

**Comment by alexeykazakov** [comment]
It would be great if we had 0.7.1 release with this fix. Then we could include it in JBoss Developer Studio 8.1.0 (JBoss Tools 4.2.3) which is going to be based on Eclipse Luna SR2.
Tern.java 0.8.1 is not so important for us because we probably will switch to Tern 0.9 eventually in the next major JBoss Developer Studio 9.0.0 release (JBoss Tools 4.3.0).
So, I hope this is an exception that we need this Tern.java 0.7.1 maintenance release and won't need such releases for every major Tern release.
@angelozerr, @pascalleclercq thank you guys!

**Comment by pascalleclercq** [comment]
Hi all,

It appears that apply  the patch : 
https://github.com/angelozerr/tern.java/commit/baa2a00fa9ee22b9fcb192d883ea568400628207

Is not trivial on the branch : 
https://github.com/angelozerr/tern.java/blob/tern.java-0.7.x-branch/eclipse/tern.eclipse.ide.core/src/tern/eclipse/ide/internal/core/resources/IDETernProjectSynchronizer.java
(code structure have changed).

What should we do ?

**Comment by angelozerr** [comment]
@pascalleclercq sorry for that. I have updated at hand the change for 0.7.0. See https://github.com/angelozerr/tern.java/blob/tern.java-0.7.x-branch/eclipse/tern.eclipse.ide.core/src/tern/eclipse/ide/internal/core/resources/IDETernFileSynchronizer.java#L106

**Comment by pascalleclercq** [comment]
@vrubezhny Hi,
can you please test  : 
http://oss.opensagres.fr/tern.repository/0.7.1/
http://oss.opensagres.fr/tern.repository/0.8.1/
http://oss.opensagres.fr/angularjs-eclipse/0.7.1-SNAPSHOT/
http://oss.opensagres.fr/angularjs-eclipse/0.8.1-SNAPSHOT/

tern.java releases are already done and angularjs-eclipse are about to be done.

Should be fine now and I'll finish the release ASAP.

**Comment by angelozerr** [comment]
Thanks @pascalleclercq for your work! @vrubezhny @alexeykazakov tell us if it's OK for you. Thanks.

**Comment by angelozerr** [comment]
@pascalleclercq I'm a little lost.

It seens that we need to create a new release because @vrubezhny have done a PR https://github.com/angelozerr/tern.java/pull/254

**Comment by paulvi** [comment]
Please keep things simple.

Just one `master` branch and incremental [versioning][http://semver.org/] is enough.

This project can be agile to release every few weeks, so there should be no need for x.x.PATCH  releases as new feature arrive and it can be just next x.MINOR.x

For end-users it should be as:

- old features work the best in the latest release
- some newer features may have bugs

**Comment by angelozerr** [comment]
> Please keep things simple.

@pascalleclercq could you read comments of @paulvi Thanks!

@vrubezhny can I close this issue?

**Comment by angelozerr** [comment]
I think this issue is done, I close it.

**Comment by vrubezhny** [comment]
@angelozerr, yes. we cannot reproduce the issue anymore. Thank you!
