### ISSUE TITLE
Release 0.9

### ISSUE THREAD

**Issue by paulvi** [angelozerr/tern.java#255]
there was bug #251 

plus there are new good features

https://github.com/angelozerr/tern.java/wiki/New-and-Noteworthy-0.9.0

**Comment by paulvi** [comment]
BTW take a look at Mockito continuous delivery http://site.mockito.org/

- Continuously delivering new version for every git push that passes the build

that happens automatically

**Comment by angelozerr** [comment]
I don't know when 0.9.0 will be released. I would like to provide for thsi release : 

 * JSON Editor: https://github.com/angelozerr/tern.java/issues/253
 * Tern Linter : https://github.com/angelozerr/tern.java/issues/244

> that happens automatically

Is it not done for tern.java? It creates SNAPSHOT version

**Comment by paulvi** [comment]
>> that happens automatically
> Is it not done for tern.java? It creates SNAPSHOT version
tern.java is good

I just showed example when when every change is treated as production ready and there is no SNAPSHOT and release version differences.

So if there was a bug like #251 we could release 0.9.0 just because there were new features as well.

**Comment by paulvi** [comment]
> JSON Editor: #253

Do you mean https://github.com/angelozerr/eclipse-wtp-json released https://github.com/angelozerr/eclipse-wtp-json/issues/2 

or embed any of alternatives?

> Tern Linter : #244

This also may be long and heavy.

**Comment by angelozerr** [comment]
> Do you mean https://github.com/angelozerr/eclipse-wtp-json

Yes. For that I must finish : 

 * Validator
 * Format
 * Fix bug with JSON model synch and editor

I would like to provide this JSON Editor because linter uses JSON.

Here for instance a screenshot of .jshintrc config for JSHint : 

![JSHInt](https://github.com/angelozerr/eclipse-wtp-json/wiki/images/JSONEditorSyntaxColoringComment.png)

> This also may be long and heavy.

Today linter starts working, I must finish : 

 * Transform TernBuilder to Tern WTP Validator.
 * Update tern-jshint, tern-eslint to support a given config file
 * Store the preferences of linter in the .tern-project

**Comment by paulvi** [comment]
ok, nice

**Comment by angelozerr** [comment]
@paulvi  we plan to create the 0.9.0 releases when @pascalleclercq  will have time to do that.

JSON Editor will be not released because it is not very stable today.

**Comment by jabby** [comment]
``` JSON Editor will be not released because it is not very stable today.

FYI I use it every day (on kepler 😢 ). it's better than js editor for json file.

**Comment by angelozerr** [comment]
> FYI I use it every day (on kepler :cry: ). it's better than js editor for json file.

Thanks, but Format, Completion, Validation are not very stable because synch of model should really improved. I don't want to do a release of the WTP JSON Editor, otherwise users will think that's it's very bugged and they will switch to other JSON Editor.

**Comment by paulvi** [comment]
Nowadays they just add word "Experimental" and release bugy, unfinished stuff... :-)

well, now seriously speaking, @angelozerr do you have any timing when 0.9 train can be released?

**Comment by angelozerr** [comment]
> Nowadays they just add word "Experimental" and release bugy, unfinished stuff... :-)

I see, but users (like me) doesn't tink like this. If tools doesn't work, they switch to another tools :)

> well, now seriously speaking, @angelozerr do you have any timing when 0.9 train can be released?

When @pascalleclercq will have time to do that, I don't know more.

**Comment by paulvi** [comment]
Just by chance noticed that @pascalleclercq has just released main 3 repositories

**Comment by angelozerr** [comment]
Done, many thank's @pascalleclercq !
