### ISSUE TITLE
Non-explicit org.apache.http.client dependency seems to cause conflicts with some third-party plugins

### ISSUE THREAD

**Issue by swingfield** [angelozerr/tern.java#273]
It looks like Eclipse Tern does not specify which version of Apache's HttpClient it requires, and this appears to be causing a conflict with some third-party plugins in my Eclipse environment.

I installed Eclipse Tern, and kept getting intermittent error dialog's popping up, associated with a "Synchronizing script resources with tern server" background job.  

The error details were 

class org.apache.http.impl.client.DefaultHttpClient does not implement the requested interface org.apache.http.client.HttpClient.

I looked into this further and noticed that the Tern plugin's MANIFEST.MF claims a dependency on org.apache.http.client, but does not explicitly identify the plugin where it should find that package.

![image](https://cloud.githubusercontent.com/assets/3903455/7438267/7e2486f0-f01e-11e4-9ff8-2da33d75b30d.png)

In most Eclipse setups, it probably gets resolved via org.apache.httpcomponents.httpclient_4.3.6.v201411290715 which, I think (?), is supplied by Eclipse itself.  Unfortunately, in my environment, the third-party plugin loads an older httpclient, and when Tern asks Eclipse to resolve its httpclient dependency, it gets handed this older version.

Would it be possible to change Tern's MANIFEST.MF so that it explicitly names the plugin that it expects to fulfill its httpclient dependency?

**Comment by angelozerr** [comment]
I do that to support both kepler and indigo.

I suggest you to install indigo. I'm afraid if I set some retriction with version, it will not work for kepler and indigo both.

**Comment by swingfield** [comment]
Hi Angelo, 

Thanks for your quick reply.  Actually I'm on Luna, but I think that switching to Indigo wouldn't help because the third-party plugin would still load up its older httpclient, which Tern would then try utilize. 

Do you think Tern could package the version of httpclient that it requires into a new, tern-supplied, plugin, and then mark that plugin as an explicit dependency? That should disambiguate how tern resolves the dependency and work on any Eclipse release.  If it's helpful, and if I'm not over-stepping my bounds, I could create a pull-request with this change in it.

**Comment by angelozerr** [comment]
Sorry I'm too on Luna.

I suppose you have several version of httpclient. I think if you use the JEE distrbitionj it should work. I will try to see this problem.

**Comment by angelozerr** [comment]
I'm woaiting for you PR to try it. Thanks.

**Comment by swingfield** [comment]
I'm using the JEE version ("Java EE IDE for Web Developers").

If I delete the third-party plugin with the old version of http client then Tern works fine.  So in that case, Tern seems to be handed a compatible version of http client.  But if I have that plugin in place, then Tern gets handed the older http client library and thus hits the error.

Sorry, didn't understand your last comment - you wanted me to try some thing?

**Comment by swingfield** [comment]
Oh sorry, I understand - you wanted me to try the JEE version. Yes, that is the version I use.

**Comment by swingfield** [comment]
I will try to create a simple plugin that demonstrates the problem, that you can drop into your eclipse to reproduce.

**Comment by swingfield** [comment]
Hi Angelo,

I set about to create a simple plugin that would show the problem.  Unfortunately, the problem seems to be not easily reproducible.  In all of my recent attempts to reproduce, Eclipse Luna picks a good plugin to resolve tern.core's org.apache.httpclient packages:
 
![image](https://cloud.githubusercontent.com/assets/3903455/7499682/85dc67e8-f3e6-11e4-8c6a-49160c924e93.png)

I can, however, force the error in a contrived experiment.  If I delete the "good" plugin from Eclipse, I can then see Eclipse give the older, incompatible httpclient plugin over to tern.core:

![image](https://cloud.githubusercontent.com/assets/3903455/7499783/0ccc60b4-f3e7-11e4-94ce-6ca45700eade.png)

But anyway, I was thinking more about this.  Do you think that tern.core could supply a minimum version of the apache http libraries in it's MANIFEST.MF file?  It seems like this would take care of the strange situation where sometimes tern.core would be given an older incompatible httpclient library.

**Comment by angelozerr** [comment]
@vrubezhny @piotrtomiak I think we need import the well package. I have tested quickly for the tern.server.nodejs plugin by setting version of http client : : 

```
Import-Package: com.eclipsesource.json;version="[0.9.2,0.9.3)",
 org.apache.http;version="4.2.5",
 org.apache.http.client;version="4.2.5",
 org.apache.http.client.methods;version="4.2.5",
 org.apache.http.conn;version="4.2.5",
 org.apache.http.entity;version="4.2.5",
 org.apache.http.impl.client;version="4.2.5",
 org.apache.http.util;version="4.2.5",
```

I use Luna but I'm afraid that it breaks Kepler for instance. Have you some recommandation?

Thanks!

**Comment by vrubezhny** [comment]
@angelozerr You cannot keep the support for Indigo & Kepler forever. Eclipse is discontinued their support. So, imho, it's OK to drop Indigo & Kepler compatibility. If you have a customer that requires such a support then suggest him the custom builds (Indigo and/or Kepler compatible, but without all the newest functionality). The main build stream should follow the Eclipse's LTS terms (at the moment the support for a version ends up in 9 months with the release of SR2). 
You may declare a support for two or more versions (like Luna+Mars), but you're not able to guarantee the full compatibility for both (or more) versions at the same time.

So, +1 to set that 'minimal required' version for http client (if you're sure that this is the minimal required appropriate version for http client to depend on)

**Comment by angelozerr** [comment]
@swingfield @vrubezhny  @piotrtomiak I have restricted the version of httpclient according my luna Eclipse (Thanks PDE). See https://github.com/angelozerr/tern.java/commit/39efa4fb484e0ce49c578d6e224d6d2ade15305d

Hope it will not problem.

@swingfield is it ok for you?

**Comment by angelozerr** [comment]
@swingfield is it ok for you?
