### ISSUE TITLE
Use module & JS type in the same icon for completion

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/tern.java#277]
Merge module icon (like YUI) with JS type (liek string, boolean) to obtain that :

![yuiicon](https://cloud.githubusercontent.com/assets/1932211/7551026/aaa43440-f678-11e4-9558-cfd60da0d2c6.png)

**Comment by angelozerr** [comment]
Done. See https://github.com/angelozerr/tern.java/wiki/New-and-Noteworthy-0.10.0#icon-for-completion--hover

**Comment by paulvi** [comment]
wow
