### ISSUE TITLE
Support for delite/deliteful

### ISSUE THREAD

**Issue by brunano21** [angelozerr/tern.java#286]
Hi,

I would like to request support for IBM delite/deliteful
https://github.com/ibm-js/delite
https://github.com/ibm-js/deliteful

Thanks!

**Comment by angelozerr** [comment]
I think to provide a very good support for delite, we should : 

 * write a tern plugin for delite. delite seems very good commented by using JSDoc, so we could generate the tern plugin for delite by using JSDoc comments. The tern plugin will able to work on Eclipse IDE, but with other editor like too Emacs, Vim, Sublime text, Atom, CodeMirror and Orion which supports tern
 * develop a new plugin like AngularJS Eclipse for the HTML part (to manage delite {} expression (highligting, compeltion, validation inside this expression)

I think we coudl provide advanced completion for define module and object literal.

My only problem is the time as I develop tern.java in my spare time. I will do that when I will find time but before I must finish other issues, but this project could be very interesting.

**Comment by angelozerr** [comment]
For information, I have started the tern plugin for delite at https://github.com/angelozerr/tern-delite

**Comment by angelozerr** [comment]
@brunano21 I have integrated tern-delite inside tern.java. See https://github.com/angelozerr/tern.java/wiki/Tern-&-Delite-support 

Note that for the moment completion for required modules are not available. I'm waiting for accept PR https://github.com/marijnh/tern/pull/560

You can play with online demo of tern-lint at http://demo-angelozerr.rhcloud.com/CodeMirror-Java/delite.html (in this demo required module is available)

**Comment by angelozerr** [comment]
Validation for required module will be available with the issur https://github.com/angelozerr/tern.java/issues/294

**Comment by angelozerr** [comment]
I close this issuue. For deliteful, for the moment I'm waiting for if it interest the delite team. If yes, please create a new issue.
