### ISSUE TITLE
JavaScript Validation

### ISSUE THREAD

**Issue by brunano21** [angelozerr/tern.java#287]
Hi,
I would like to ask if tern has a workaround to let to Eclipse working fine when using some JS keywords, even if the strict validation is enabled.

What I mean is the following:
if you have the JS strict validation into Eclipse enabled and if you use keywords as `catch`, you will get an error on that - this is normal! But: since I'm using a third JS library (Promise) I get a lot of errors because it makes a deep use of `catch` word. You could say: "well, please disable the strict validation" but I can not, because I need it for my own code. So the question is: does tern (or any its modules) provide a way to allow some JS keywords, even if the strict validation is enabled?

    p1.then(function(value) {
      console.log(value); // "Success!"
      throw "oh, no!";
    }).catch(function(e) {
      console.log(e); // "oh, no!"
    })
For reference: 
This is a bug report raised on eclipse repo some time ago:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=457830

Regards,

**Comment by angelozerr** [comment]
tern.java has her own WTP Tern Validator. It doesn't disable the JSDT Validator.

Perhaps if you disable JSDT Validator and you use https://github.com/angelozerr/tern.java/wiki/Tern-Linter-Lint it will work perhaps?

If tern validator must be improved (with your Promise lib) please create an issue at https://github.com/angelozerr/tern-lint/issues with a sample.

**Comment by brunano21** [comment]
The main problem is that the standard WTP does not allow the use of JavaScript languages keywords, giving so errors when using them and reporting those error into the Problems view. The only way to not showing those errors into the Problems view is to exclude the folder/file that is generating errors (Project Properties -> JavaScript -> Include Path). This solution obviously is not feasible! 
PS: I'm on Eclipse Luna 4.4.1

**Comment by angelozerr** [comment]
JSDT doesn't provide a WTP Validator for JavaScript. It is based on Builder. To disable it, you go at Properties project Buillders and uncheck JavaScript Validator.

**Comment by angelozerr** [comment]
It's a problem with JSDT, It seems that if you disable "Strict mode", the validator doesn't report problem. 

@brunano21 as it's a problem with JSDT, I close this issue. Please post a bug to JSDT, thanks!
