### ISSUE TITLE
Release 0.10.0

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/tern.java#288]
@vrubezhny @dgolovin when @pascalleclercq will have time, release can be created.

**Comment by vrubezhny** [comment]
That's great news!

**Comment by angelozerr** [comment]
Done http://oss.opensagres.fr/tern.repository/0.10.0/

Many thanbks @pascalleclercq !

**Comment by angelozerr** [comment]
Next release is for AngularJS Eclipse.

**Comment by angelozerr** [comment]
All release was done (tern.java, AngularJ SEclipse WTP WebResources) Thanks @pascalleclercq!

@vrubezhny @dgolovin for your information, released is done.
