### ISSUE TITLE
Include/Exclude paths with minimatch

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/tern.java#292]
https://github.com/isaacs/minimatch written in JavaScript is used in a lot of project to match include/exclude path for files. With minimatch you can write complex regexp to match something (a file for instance).

I have started to port(very quickly) minimatch in Java https://github.com/angelozerr/minimatch.java and I would like to use it to support include/exclude files for tern script path to fix https://github.com/angelozerr/tern.java/issues/150 and https://github.com/angelozerr/tern.java/issues/168. With that I could : 

 * use include/exclude information from JSDT.
 * provide an UI to type complex include/exclude paths.
 * use information like bower.json to know which files are in the tern scope. See https://github.com/jabby/sample-4-angularjs-eclipse

@vrubezhny @dgolovin @mickaelistria @maxandersen @pascalleclercq @gamerson @PaulVI @fbricon @piotrtomiak @jabby what do you think about that?

**Comment by jabby** [comment]
FYI, in Eclipse Mars, the JSDT have a new ability. By default the jsdt include path deal with some know locations. More information here. https://bugs.eclipse.org/bugs/show_bug.cgi?id=462385

For an update about how bower works, I think we should use this explanation https://bugs.eclipse.org/bugs/show_bug.cgi?id=462115#c6

**Comment by angelozerr** [comment]
@jabby thanks for your info. tern.java synchronize tern script path from JSDT Install path, but today include/excclude path are not managed. I'm working on this issue.

**Comment by angelozerr** [comment]
@vrubezhny @dgolovin @mickaelistria @maxandersen @pascalleclercq @gamerson @PaulVI @fbricon @piotrtomiak @jabby I have integrated minimatch.java to support include/eclude path inside tern.java. JSDT Install Path are translated to tern script path.

It's a big refactoring, and I must write tests now.  minimatch.java will provide the capability to write complex pattern that we can use inside bower.json (I will study how to integrate bower.json to include/exclude files by follwing instruction of https://github.com/jabby/sample-4-angularjs-eclipse)

I think there will have bugs, so don't hesitate to create PR and tests, thanks!

**Comment by angelozerr** [comment]
@vrubezhny @dgolovin @mickaelistria @maxandersen @pascalleclercq @gamerson @PaulVI @fbricon @piotrtomiak @jabby I have finished my work to support include/exclude for completion, and validation (with WTP tern Validator).

Today include/exclude are confugured only with JSDT Install Path. In the future we could configure it : 

 * with UI preferences to set complex pattern (that minimatch supports)
 * with some extension like bower to use bower.json to exclude files.

It is a very important changes inside tren.java, so please test, give me your feedback, and provide PR to fix some bugs, thanks!

I would like to create JUnit for this important feature.

**Comment by angelozerr** [comment]
I close this issue. Please read https://github.com/angelozerr/tern.java/wiki/New-and-Noteworthy-1.0.0#includeexclude-tern-script-paths

For JUnit I have created this issue https://github.com/angelozerr/tern.java/issues/299
