### ISSUE TITLE
JSHint: .jshintrc file location

### ISSUE THREAD

**Issue by brunano21** [angelozerr/tern.java#297]
At the moment, it's possible to load a .jshintrc file that lives only in the project or in a project's subfolder.
Would be handful to provide also a file which lives outside of the project. In fact when you are going to select a custom config file for jshint, potential .jshintrc files are searched only within project's folder. 

Example:
Suppose we have the following folders organization:

    + root
        + proj A
            + js
            + html
            + ...
        + proj B
            + js
            + html
            + ...
    - .jshintrc
    - ...
In this case the external .jshintrc file would be shared between projects A and B, avoiding so to replicate the file for each project.

**Comment by brunano21** [comment]
Note, if you edit by hand the .tern-project file and use the following:
`"jshint":{"configFile":"../.jshindddtrc"}`
the validation works well, I suppose the file is found and used for the jshint validation.

However, if the file does not exist, no error is returned. I'm not sure if this is good or not. And furthermore, a JSHint validation is executed anyway - I do not know which file is used for rules definition.

**Comment by angelozerr** [comment]
@brunano21 please install last version of tern.java:

> However, if the file does not exist, no error is returned.

It should throw an exception in the tern console.

>  if you edit by hand the .tern-project f

Now you can choose a location from project, workspace or filesystem.
