### ISSUE TITLE
Enide (Studio) 2015 for Java, JavaScript and tool dev

### ISSUE THREAD

**Issue by paulvi** [angelozerr/tern.java#298]
Enide 2015 http://www.nodeclipse.org/enide/2015/ is released

that includes Nodeclipse and AngluarJS, TernIDE and webresources, and all for plugin development as in IDE for committers (excluding CVS) and all dev resources.

Please give a try. 

Sources and suggestions at
https://github.com/Nodeclipse/packages

**Comment by angelozerr** [comment]
@paulvi thanks for your info. 

I close this issue.
