### ISSUE TITLE
Question: When changing .tern-project how to make TernIDE refresh markers for current file?

### ISSUE THREAD

**Issue by paulvi** [angelozerr/tern.java#300]
When changing .tern-project (manually or via properties Dialog)   
how to make TernIDE refresh markers for current file?

I try reopening files or reopening project but it does not always give the same result.

ref https://github.com/angelozerr/tern-lint/issues/46

**Comment by angelozerr** [comment]
When you change .tern-project it reload trrn server

I dont know how to refresh the wtp tern validator with java code

**Comment by paulvi** [comment]
Ok, changing `.tern-project` reloads tern server, but the error markers stays the same.

So thing to try would reopen file or close and open project ?

**Comment by angelozerr** [comment]
I must studio how to refresh wtp validator with java code

**Comment by angelozerr** [comment]
Done

![](https://github.com/angelozerr/tern.java/wiki/images/EclipseIDE_ValidationSettingsChangedDialog.png)

See https://github.com/angelozerr/tern.java/wiki/New-and-Noteworthy-1.0.0#validation-settings-changed

**Comment by paulvi** [comment]
Can there be preference to re-validate project automatically on any .tern-project change

**Comment by angelozerr** [comment]
I have done the same thing than WTP Validator (eg : you modify HTML validator preferences).

We could add this preferences, but no time to do that today.
