### ISSUE TITLE
tern.java & ES6 support

### ISSUE THREAD

**Issue by paulvi** [angelozerr/tern.java#308]
Copied from email

Hi Guys,

At first I hope you are in fit after your holliday (or perhaps you are in holliday again).

I contact you to give you news about :tern.java, AngularJS Eclipse and ternjs.

1) tern.java 1.0.0-SNAPSHOT

It provides validation by using JSDoc, advanced completion for browser (CSS selectors, element IDs), RequireJS required module completion, hyperlink support, improve of ES6 Promise, and Tern Explorer (by waiting that JSDT Outline will give the capability to extend it)

Please read https://github.com/angelozerr/tern.java/wiki/New-and-Noteworthy-1.0.0 for more info.

2)  AngularJS Eclipse 1.0.0-SNAPSHOT

I'm trying to improve a lot completion, hyperlink for angular like support for depdnencies module, templateUrl, etc

See https://github.com/angelozerr/angularjs-eclipse/wiki/New-and-Noteworthy-1.0.0 for more info.

3) ternjs & ES6 support

I tell me if you could sponsor https://www.bountysource.com/issues/1141202-support-es6-features to provide full ES6 support inside Eclipse (read last comment to know the features of tern ES6).

I don't know ES6, but as tern uses acorn which support ES6,  have tried to integrates ES6 class inside Tern Explorer (not commited)

![ternexploreres6](https://cloud.githubusercontent.com/assets/1614482/9309287/2c5ba098-453b-11e5-9e0c-b3e35a554aa2.png)

So if your company could sponsor  https://www.bountysource.com/issues/1141202-support-es6-features it should be very cool, I could integrate it and provides advanced ES6 support inside Eclipse!

Have a nice day.

Regard's Angelo
​

**Comment by paulvi** [comment]
When talking about looking for bounty sponsors, I can suggest posting to http://www.nodeclipse.org/

Just write text to publish or even PR see https://github.com/Nodeclipse/www.nodeclipse.org/blob/gh-pages/index.html#L207

TernIDE effort is also effort that should have some feedback loop via asking for bounties.

Nodeclipse is maybe too, but had no time or talks about that recently.

**Comment by paulvi** [comment]
ref https://github.com/marijnh/tern/issues/116

**Comment by angelozerr** [comment]
tern-es6 was integrated. I close this issue.

**Comment by paulvi** [comment]
great part of 1.1 #309

**Comment by angelozerr** [comment]
thanks @paulvi !
