### ISSUE TITLE
Release 1.1.0

### ISSUE THREAD

**Issue by paulvi** [angelozerr/tern.java#309]
Why there is https://github.com/angelozerr/tern.java/milestones/1.0.1 ?
Was there bug in 1.0.0 ?

If not, 1.1.0 should be next as semver.org

**Comment by angelozerr** [comment]
Yes it's an error. Next version will be https://github.com/angelozerr/tern.java/milestones/1.1.0

**Comment by paulvi** [comment]
OK, also [comment](https://github.com/angelozerr/tern.java/issues/306#issuecomment-136648431) should be here

**Comment by paulvi** [comment]
By the way, I am going to cut and release Nodeclipse 1.0 see http://www.nodeclipse.org/history

**Comment by angelozerr** [comment]
Pay attention with 1.1.0, it is not released and there are some bugs again like node mongoose, etc which works not more.

**Comment by paulvi** [comment]
It is OK, there is dependency or expectation of particular version.

For users recommendation would be just to have the latest stable version 
https://github.com/angelozerr/angularjs-eclipse/issues/163

**Comment by angelozerr** [comment]
Done, thank a lot @pascalleclercq !
