### ISSUE TITLE
[node] Guess required node module when require completion is applied

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/tern.java#311]

**Comment by angelozerr** [comment]
Here the result with required node module : 

![test](https://cloud.githubusercontent.com/assets/1932211/9663922/305c0a64-5267-11e5-8cc6-35e5425d288e.gif)

**Comment by paulvi** [comment]
Looks very neat

How do you record .gif ?

**Comment by angelozerr** [comment]
> Looks very neat

A little bug must be fixed, but it's soon finished and other tern plugin will able to contribute to tern-guess-type to support this feature.

> How do you record .gif ?

I searched a very simple free software which does that and I have found http://www.cockos.com/licecap/

**Comment by paulvi** [comment]
BTW, usually user has already types something as

```js
var ...
       ....
     http = require(
  

```

convention would suggest to use variable name as first suggested module name.

**Comment by angelozerr** [comment]
I don't know if it's easy to implement. Please create an issue at https://github.com/angelozerr/tern-guess-types/issues

**Comment by paulvi** [comment]
This usually is templating.

In Node if variable is named `http` then it is likely meat to be for `require("http")`
