### ISSUE TITLE
UI Preferences for ECMAScript compliance + JSDoc

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/tern.java#312]
tern-es6 support is integrating. So now we need a better UI for ECMAScript settings (and JSDoc)

![ecmascriptuiprefs](https://cloud.githubusercontent.com/assets/1932211/9664034/c0a9f428-5267-11e5-9eb6-92d17befd130.png)

IMPORTANT: I will remove ECMAScript and JSDoc from the Tern / Modules.

@vrubezhny @dgolovin @mickaelistria @maxandersen @pascalleclercq @gamerson @PaulVI @fbricon @piotrtomiak @jabby what do you think about this UI, description are clear?

**Comment by paulvi** [comment]
It becomes closer to JSDT, and it should look more like

![image](https://cloud.githubusercontent.com/assets/1614482/9693781/a11d537e-5385-11e5-8dc3-364b7aad6829.png)

![image](https://cloud.githubusercontent.com/assets/1614482/9693785/a96a775a-5385-11e5-8710-49509af4ca17.png)

JSDoc checkbox labels are to long, can you do it shorter but add tip on mouse over

**Comment by mickaelistria** [comment]
@angelozerr Also, not sure if it's related to your question, but the Tern node should probably be a child of the "JavaScript" node in preferences. Many JavaScript developers who are "just" users don't know about Tern, and while tweaking JS stuff, they'll search under the "JavaScript" node.

**Comment by angelozerr** [comment]
> It becomes closer to JSDT

Yes but JSDT uses that only for Validation. Tern uses this ECMA config for completion too (and soon validation when tern-lint will support validation for ES modules, Class).

> and it should look more like

What do you mean? Change "Version" to "ECMAScript compliance level"? For JSDoc, it's not the same than JSDT. The JSDoc Tern config is used to know if JSDoc must be used or not, but it doesn't validate the syntax of JSDoc.

**Comment by angelozerr** [comment]
> Also, not sure if it's related to your question, but the Tern node should probably be a child of the "JavaScript" node in preferences

The problem with that is "JavaScript" node belongs to JSDT and Tern UI have none dependencies to JSDT. If I do that, I must change my all screenshot of wiki (a lot of work too).

**Comment by maxandersen** [comment]
you can declare the same category (JavaScript) without having a hard dependency on JSDT and it will still work.
So I would recommend aligning these instead of spreading the settings for javascript across preferences.

**Comment by angelozerr** [comment]
@maxandersen as I have explained, you can use tern without JSDT.

If I set Tern property page in the JavaScript category (by using category="org.eclipse.wst.jsdt.internal.ui.preferences.JavaScriptMainPage" ) : 

 * if project has JSDT nature, there is JavaScript -> Tern 
 * if project has NOT JSDT nature, there is Tern

So to avoid having those 2 cases, I prefer having Tern as root node.

**Comment by mickaelistria** [comment]
If I understood correctly, Max is suggesting you to "copy" the JavaScript category in Tern, either reusing only the label or even the categoryId if it works better. If you do that, then the Preference page should merge the 2 JavaScript categories, providing a single and consistent JavaScript node in Preference UI.

> So to avoid having those 2 cases, I prefer having Tern as root node.

The question is more "what would user prefer" ;)

**Comment by angelozerr** [comment]
> If I understood correctly, Max is suggesting you to "copy" the JavaScript category in Tern, either reusing only the label or even the categoryId if it works better.

@mickaelistria I have tried several means, but it doesn't work -(:

 * If my project has JSDT Nature, I can have JavaScript/Tern hierarchy if I do like this : 

```xml
      <page
            name="%javaScriptPropertiesPageName"
            id="org.eclipse.wst.jsdt.internal.ui.preferences.JavaScriptMainPage">
         <enabledWhen>
		     <adapt type="org.eclipse.core.resources.IProject">
                  <test property="tern.eclipse.ide.ui.isTernProject" />
		     </adapt>         
         </enabledWhen>
      </page>
      <page
            name="%TernMainPropertyPage.name"        
            class="tern.eclipse.ide.ui.properties.TernMainPropertyPage"
            id="tern.eclipse.ide.ui.properties"
            category="org.eclipse.wst.jsdt.internal.ui.preferences.JavaScriptMainPage" >
         <enabledWhen>
		     <adapt type="org.eclipse.core.resources.IProject">
                  <test property="tern.eclipse.ide.ui.isTernProject" />
		     </adapt>         
         </enabledWhen>
      </page>
```

 * If my project has NOT JSDT Nature, I have Tern hierarchy without JavaScript root node.

If I declare a class MyClass with JSDT ID:

```xml
<page
            name="JavaScript"        
            class="MyClass"
            id="org.eclipse.wst.jsdt.internal.ui.preferences.JavaScriptMainPage">
```

It works when project has not JSDT nature, but when project has JSDT nature, the JavaSCript displays MyCLass instead of JSDT JavaScriptMainPage.

The only solution that I see is to declare class with org.eclipse.wst.jsdt.internal.ui.preferences.JavaScriptMainPage but my plugin will have an hard dependency to JSDT

> The question is more "what would user prefer" ;)

I agree! It seems you wish that, but I don't know ho wto do that? Any contribution are welcome!

**Comment by mickaelistria** [comment]
Thanks for those technical details. I now understand better the issue, 
and it's indeed an annoying situation... I have no idea how to make it 
work as expected at the moment. However, I suggest that, keeping the 
current approach, instead of Tern, you name the page "Tern for 
JavaScript" or "JavaScript/Tern". I believe it's important that the work 
JavaScript can be found in the preference tree, with or without JSDT.

**Comment by maxandersen** [comment]
I don't know any user who prefers to jump across multiple JSDT preferences to use javascript.

This is just an example of where I think tern would be much better of having dependency on JSDT instead of trying be separate and causing additional confusion and inconsistency.

**Comment by mickaelistria** [comment]
By the way, I agree with @maxandersen on that part. I believe the constraint of avoiding any dependency against JSDT actually has a cost for users who are going to find the UI too scattered, continuing to feel that "Eclipse is not consistent" (quoting many Eclipse users and developers there).
So IMO removing this constraint and adding a dep to JSDT would make usage of Tern more straightforward.

**Comment by angelozerr** [comment]
@maxandersen @mickaelistria I prefer having none dependencies to JSDT for Core/UI because some other plugins could use tern.java without JSDT which have a lot of dependencies too. The glue between Tern/JSDT are done with those plugins https://github.com/angelozerr/tern.java/tree/master/eclipse/jsdt

But as you prefer really having Tern Preferences inside JavaScript node, I will change the category of Tern Preferences to have : 

 * JavaScript/Tern if project has JSDT nature.
 * Tern if the project has not the JSDT nature.

Are you Ok?

Could you tell me abou my initial questionn please if it's OK, thanks!

* Look for JSDoc-style type declarations, try to parse them and add them to the inferred types?
 * Assign a higher-than-default weight to the types it finds in comments, and thus overrides inferred types?

**Comment by mickaelistria** [comment]
> But as you prefer really having Tern Preferences inside JavaScript node, I will change the category of Tern Preferences
I think it's indeed better.

> Look for JSDoc-style type declarations, try to parse them and add them to the inferred types?
What about the shorter "Infer Types from JSDoc-style type declations". It's generally a bad UI pattern to have a question for a checkbox, checkbox usually tell their affirmative value.

> Assign a higher-than-default weight to the types it finds in comments, and thus overrides inferred types?
What about "Put higher priority to types found in comments (override inferred types)"

Maybe the page would rather use the SWT Group widget to group parts (ECMAScript, JSDoc) in a more visible way.

**Comment by angelozerr** [comment]
> I think it's indeed better.

Done via https://github.com/angelozerr/tern.java/commit/4a2f01bfac8b70fc36653f4cacf046af3328a7fb

**Comment by paulvi** [comment]
[> JSDoc checkbox labels are to long, can you do it shorter but add tip on mouse over](https://github.com/angelozerr/tern.java/issues/312#issuecomment-137844335)

Those label are long, second Michael

>> Look for JSDoc-style type declarations, try to parse them and add them to the inferred types?

> Infer types from JSDoc-style type declarations

:+1: 

>> Assign a higher-than-default weight to the types it finds in comments, and thus overrides inferred types?

> Put higher priority to types found in comments (override inferred types)

"make JSDoc-style type declarations to be higher priority"

Can anything be higher than that?

----

JavaScript in preferences should not mean only JSDT.  
But if Tern tree is inside JavaScript, it should respect and use those settings.

If not, still name like "JavaScript with Tern" would put those tree next to "JavaScript" (with JSDT)

![image](https://cloud.githubusercontent.com/assets/1614482/9739975/f3583cf6-5684-11e5-8d4e-0fc900ba2afc.png)

**Comment by paulvi** [comment]
Well, this thread is named "UI Preferences for ECMAScript compliance + JSDoc"

while there is a lot discussion about "Integration with JSDT" that is #248

**Comment by paulvi** [comment]
@angelozerr 

- [ ] UI Preferences for ECMAScript compliance + JSDoc should not be on Tern root page,
but on some page named with words "JavaScript", "ECMAScript", "Validation", "JSDoc"

like in JSDT 

![image](https://cloud.githubusercontent.com/assets/1614482/9740543/e4ff818e-5687-11e5-98a7-f7c40806823a.png)


![](https://cloud.githubusercontent.com/assets/1932211/9664034/c0a9f428-5267-11e5-9eb6-92d17befd130.png)

**Comment by paulvi** [comment]
- [ ] There should be workspace wide preferences https://github.com/angelozerr/tern.java/issues/316

**Comment by maxandersen** [comment]
@paulvi since every UI in Tern will often if not always conflict with JSDT the topic of JSDT integration cannot really be limited to #248.

@angelozerr I like your suggested compromise of having JavaScript/Tern as the category.
Don't understand why you would want to have 2 different preference nodes dependent on what nature is on it. Whether the project has a JSDT nature and/or Tern does not really change it is still JavaScript/Tern.
Doing it with 2 will just expose internal implementation details to the user that is really not necessary.

**Comment by angelozerr** [comment]
> What about the shorter "Infer Types from JSDoc-style type declations". It's generally a bad UI pattern to have a question for a checkbox, checkbox usually tell their affirmative value.

Ok, so you mean that I must remove the `?`

> "use JSDoc-style type declarations"
> "treat JSDoc-style type declarations as higher priority"

@mickaelistria @maxandersen is suggestion of @paulvi please you? Just to explain "treat JSDoc-style type declarations as higher priority", it means that tern uses only the type coming from teh JSDoc. Take a sample : 

```javascript
/**
 * @type {String}
 */
 var a = 10;
```

 * without this option. `a' is a String and Number type.
 * with this option. `a' is a only String type.

> But if Tern tree is inside JavaScript, it should respect and use those settings.

Yes I agree, Tern for global preferences must be inside JavaScript.

> UI Preferences for ECMAScript compliance + JSDoc should not be on Tern root page, but on some sub-page named with words "JavaScript", "ECMAScript", "Validation", "JSDoc"

Yes it can be a good idea. @maxandersen, @mickaelistria what do you think about that? But pay attention JSDoc of JSDT preferences is for validation of JSDoc content although JSDT of Tern is for using JSDoc for retrieve type for the inference engine. 

> Don't understand why you would want to have 2 different preference nodes dependent on what nature is on it.

I would like to do that, but I don't know how to do that https://github.com/angelozerr/tern.java/issues/312#issuecomment-138213689. I have an idea, I will try it.

**Comment by mickaelistria** [comment]
> Ok, so you mean that I must remove the ?

Yes, that's the usual convention.

I'm ok with the "use JSDoc-style type declarations" label.
For the 2nd according to your explanation, wouldn't "When JSDoc-style declarations are available, Infer only from those and exclude other inferences" be more accurate then? In any case, this checkbox seems to deserve an additional tooltip to give a more detailed explanation, and showing your example.

**Comment by angelozerr** [comment]
Thanks @mickaelistria! And what dou think about "UI Preferences for ECMAScript compliance + JSDoc should not be on Tern root page" : 

 * JavaScript
  * Tern
     * ECMAScript
     * JSDoc
     * Modules
     * Validation

**Comment by mickaelistria** [comment]
It seems to me that the 2 JSDoc settings here are not to configure JSDoc itself, but to configure how Tern will use JSDoc to infer types. So IMO, this is a core top-level setting and would rather be in the Tern top-level page (or a dedicated "Inference" page).
Maybe those options could be shown on several pages? (on JSDoc page, and on the Tern page or an Inference page)
However, I'm not 100% confident what I suggest is actually what's best ;)

**Comment by angelozerr** [comment]
> but to configure how Tern will use JSDoc to infer types.

Exactly!

> However, I'm not 100% confident what I suggest is actually what's best ;)

Ok, so perhaps I keep my initial suggestion  (set ECMAScript + JSDoc in the Tern property page).

> Maybe the page would rather use the SWT Group widget to group parts (ECMAScript, JSDoc) in a more visible way.

it is already used, no?

**Comment by mickaelistria** [comment]
>>    Maybe the page would rather use the SWT Group widget to group parts (ECMAScript, JSDoc) in a more visible way.

> it is already used, no?

Yeah sorry, it's just that they were much visible on the sceenshot, but yes, there are groups.

**Comment by angelozerr** [comment]
> "When JSDoc-style declarations are available, Infer only from those and exclude other inferences" be more accurate then?

The ternjs code uses priority for type. When JSDoc "strong" option is setted, it set the type coming from JSDoc with hight priority.

**Comment by angelozerr** [comment]
@paulvi @maxandersen @mickaelistria after our discussion, here the result : 

![ecmascriptuiprefs](https://cloud.githubusercontent.com/assets/1932211/9760605/bda3eb88-56f6-11e5-810e-df541ecc2af3.png)

Is it OK for you?

**Comment by mickaelistria** [comment]
I like it.
(not related, but having JSHint under JavaScript would be nice too)

**Comment by angelozerr** [comment]
> I like it.

Cool! 

> (not related, but having JSHint under JavaScript would be nice too)

JSHint is not my plugin https://github.com/eclipsesource/jshint-eclipse

But Tern provides teh capability to validate with JSHint https://github.com/angelozerr/tern.java/wiki/Tern-Linter-JSHint

**Comment by angelozerr** [comment]
Ok I close this issue. thanks @paulvi @maxandersen @mickaelistria for your feedback. If you need some update, please create a new issues.

**Comment by angelozerr** [comment]
@maxandersen I have not found solution to add JavaScript category when project has not JSDT nature. So we will have 2 cases that I hav eexplained here https://github.com/angelozerr/tern.java/wiki/New-and-Noteworthy-1.1.0#tern-property-pages

**Comment by maxandersen** [comment]
looks like a good compromise. I can't see a way around having a unified preference without Tern depending on JSDT, so as long as that split is there this will be the consequence.
