### ISSUE TITLE
Tern Explorer is empty

### ISSUE THREAD

**Issue by paulvi** [angelozerr/tern.java#313]
When/how TernExplorer is updated

![image](https://cloud.githubusercontent.com/assets/1614482/9694538/21488996-538c-11e5-9691-64761655aeee.png)

```js
var fs = require("fs");

var folderName = __dirname;  // for current folder
var maxlength = 90;

function getFiles(dir, files_) {
	files_ = files_ || [];
	var files = fs.readdirSync(dir);
	for ( var i in files) {
		var name = dir + '/' + files[i];
		if (fs.statSync(name).isDirectory()) {
			getFiles(name, files_);
		} else {
			files_.push(name);
		}
	}
	return files_;
}

var files = getFiles(folderName);
console.log(files);
for (var i = 0; i < files.length; i++) {
	var filename = files[i];
	if (filename.length > maxlength) {
		console.log("Deleting " + filename);
		fs.unlinkSync(filename);
	}
}
```

**Comment by angelozerr** [comment]
Have you checked Outline tern modules like explained at  https://github.com/angelozerr/tern.java/wiki/Tern-Outline-support

This Tern Explorer is refreshed as soon as you are typing JS code. If it doesn't work, please try with a simple code like "var a;".

**Comment by paulvi** [comment]
> open Project Properties, click on Tern / Modules item and select the Outline tern plugin (ECMAScript tern plugin must be selected too) :

- [ ] Plugin and View should have the same name, e.g. "Tern Outline(r)" or "JavaScript Outline(r)" or just "Outline_r_"

- [ ] There should be workspace-wide preference

**Comment by paulvi** [comment]
I went into project properties, checked Outline, but Tern Explorer is still empty.

Here is current  `.tern-project`

```js
{"ide":{},"libs":["ecma5"],"plugins":{"outline":{},"node":{}}}
```

**Comment by angelozerr** [comment]
@paulvi I think it's a bug, I suggest you to open Tern Console and you will see errors. Please try with a simple code like "var a".

**Comment by angelozerr** [comment]
@paulvi I have fixed teh bug, but there are again a little bug which doesn't display your fs variable.

**Comment by angelozerr** [comment]
@paulvi I have fixed the problem, please test in your side. Here the result:

![fixternexplorerempty](https://cloud.githubusercontent.com/assets/1932211/9787752/97772068-57c5-11e5-83ca-ce9d7e035270.png)
