### ISSUE TITLE
Request for Foundation5 ContentAssist support

### ISSUE THREAD

**Issue by pgnd** [angelozerr/tern.java#318]
Similar to existing Bootstrap3 support, tern-bootstrap, requesting inclusion of ContentAssist for Zurb's Foundation 5 (http://foundation.zurb.com/)

The js API docs are here

  http://foundation.zurb.com/docs/javascript.html

Foundation5's source repo is here: https://github.com/zurb/foundation

Foundation6 is coming soon: http://zurb.com/article/1403/foundation-6-prototype-to-production

**Comment by angelozerr** [comment]
It seems that Fondation 5 provides too : 

 * utilities class : http://foundation.zurb.com/docs/javascript-utilities.html
 * widget classes like tabs http://foundation.zurb.com/docs/components/tabs.html#tabs-deeplink-3

It seems doc is not generated from JS code (no JSDoc comments) so we must write at hand the JSON Type Definition.

**Comment by pgnd** [comment]
Re: Doc, take a look at this comment from a Zurb employee

https://github.com/zurb/foundation/issues/4710

	gakimball commented on Jan 30

		@adamj88 Yes! We're building a tool that will generate documentation from Hologram,
		SassDoc, and JSDoc. This will also make it easier to design more detailed documentation
		for the variables and mixins. (See the Neat documentation for an example.)

Not yet sure if that's at all helpful
