### ISSUE TITLE
Tern Explorer - one var is missing

### ISSUE THREAD

**Issue by paulvi** [angelozerr/tern.java#319]
in example from #313 `fs` in not in view

![image](https://cloud.githubusercontent.com/assets/1614482/9837457/0d2750d6-5a72-11e5-926c-a6c787ecb8a1.png)

**Comment by paulvi** [comment]
well, maybe that is version issue

![](https://cloud.githubusercontent.com/assets/1932211/9787752/97772068-57c5-11e5-83ca-ce9d7e035270.png)

**Comment by angelozerr** [comment]
> well, maybe that is version issue

Yes it was a problem that I had fixed https://github.com/angelozerr/tern-outline/commit/623e2268267d1cbc596a12a5c646e8b1315294e0#diff-3ceb5f0d824cdd1f0fd86b92126d1737R76

Thanks @paulvi to play with Tern Explorer. I think tern-outline starts working good, but there are 2 improvements to do:

 * improve performance whith a big JavaScript files (Eclipse can freeze when UI is refreshed, I must study how to fix that (refresh only the tree item which must be refreshed, or support outlien without searching type?)

 * ES6 support like display ES6 class, etc

 * display angular controller, etc in the outline, etc

Please create you issues at https://github.com/angelozerr/tern-outline/issues if you find bug with tern explorer and you wish some improvement. Thanks!

**Comment by angelozerr** [comment]
@paulvi why have you reopned this issue? It is fixed. Please retry with last version of tern.java.

**Comment by paulvi** [comment]
because you have mentioned several points, and possibly there are no open issues for those.

it is up to you.

**Comment by angelozerr** [comment]
> because you have mentioned several points, and possibly there are no open issues for those.

Ok I understand. I will create an issue per idea and close this issue.

**Comment by angelozerr** [comment]
@paulvi I close this issue, I have created several issues:

 * https://github.com/angelozerr/tern.java/issues/335
 * https://github.com/angelozerr/tern.java/issues/336
 * https://github.com/angelozerr/tern.java/issues/337
