### ISSUE TITLE
Tern.java should not propose the Hyperlinks (like "Tern - Go to definition") if it's really cannot execute the hyperlink

### ISSUE THREAD

**Issue by vrubezhny** [angelozerr/tern.java#324]
Since there could be more than one Hyperlink shown for a position in JSP/HTML text, the Hyperlinks are to be shown only if the real transition is available for the Hyperlink.

In some cases, "Tern - Go to definition" link is shown first in the link of possible hyperlinks, but if the transition is not possible for the Hyperlink, no other Hyperlinks can be executed by defaullt (by pressing "F3" shortcut-key).

See: https://issues.jboss.org/browse/JBIDE-20722 ("Tern - Go to definition" hyperlink opens nothing) - for the reference.

**Comment by angelozerr** [comment]
@vrubezhny if you wish I display "Tern - Go to definition" link  only if tern can retrieve definition, it means that I must call every time tern server to execute the find of definition when user open hyperlink. I have done this choice to execute the call of tern server only when user opens hyperlink (and not when he does Ctrl+Click) to have a good performance when user does Ctrl+Click (it avoids freeze of Eclipse if ternjs takes time)

What do you think about that?

**Comment by alexeykazakov** [comment]
Can we do something with these tern hyperlinks so they won't be the first one if there are other hyperlinks available? @dazarov do you know if it's possible?

**Comment by angelozerr** [comment]
An other idea to avoid freezing Eclipse when user does Ctrl+Click, is that we could execute tern server with async mode like @piotrtomiak have done for async completion https://github.com/angelozerr/tern.java/wiki/New-and-Noteworthy-0.9.0#async-tern-completion

@piotrtomiak do you know if it's possible and easy to call "definition" query type with asynch mode like you have done for "completion" query type?

**Comment by angelozerr** [comment]
@vrubezhny @alexeykazakov now I return Hyperlink for Tern & Angular only if definition can be found. The execution of the tern "definition" query is executed with async mode, it was easy to do (great job @piotrtomiak!)

Tell me if it works in your side.

**Comment by piotrtomiak** [comment]
@angelozerr heh I haven't even been able to reply, you were so fast :P

**Comment by dazarov** [comment]
@alexeykazakov, we cannot cotrol order of hyperlinks. 

But there is something we can do..
We can use keyModifier for Hyperlink Detector (See: http://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fextension-points%2Forg_eclipse_ui_workbench_texteditor_hyperlinkDetectors.html)

So we can set some (for instance: Alt+Shift) modifier for "Tern - Go to definition"
Not sure if it is a good idea. Just letting you know about this opportunity :)

**Comment by angelozerr** [comment]
@vrubezhny have you tested, can I close this issue?

**Comment by angelozerr** [comment]
@vrubezhny have you tested, can I close this issue?

**Comment by angelozerr** [comment]
@vrubezhny I close this issue, but if you find problem please reopen it.
