### ISSUE TITLE
Contributors list removed from headers

### ISSUE THREAD

**Issue by piotrtomiak** [angelozerr/tern.java#326]
@angelozerr @pascalleclercq I have started merging the newest version of Tern with our codebase and I've found that the license/contributor headers have been cleared up and all information about our contributions to your project is no longer present in the source code. Everything was cleared up with commit 752e45652a3422d099f6c1fff3e53c9bdb8b8506.

**Comment by angelozerr** [comment]
argh -( sorry!!!!!!!!! @pascalleclercq is it possible to fix that (hope it will not an awfull task)

**Comment by angelozerr** [comment]
@pascalleclercq if you have no time, I will do that at hand (I'm preparing a big refactoring with Tern Module Metadata for https://github.com/angelozerr/tern.java/issues/327)

**Comment by piotrtomiak** [comment]
@angelozerr thanks! Maybe some partial commit revert would work?

**Comment by angelozerr** [comment]
> Maybe some partial commit revert would work?

I will do that at hand soon.

**Comment by angelozerr** [comment]
@piotrtomiak I have fixed the problem (hope I have not done some errors)

@vrubezhny I have not seen your name in the header, tell me of I must change something. Thanks.

**Comment by vrubezhny** [comment]
@angelozerr  I'm ok with these changes. (there was no my name referenced previously so actually any change on header is acceptable for me... in case if you're not changing the license, off course :) )

**Comment by angelozerr** [comment]
> @angelozerr I'm ok with these changes. (there was no my name referenced previously so actually any change on header is acceptable for me... 

Next time, I think it should b every cool if you had your name in the license header, you provide too so cool feature. Thanks.

> in case if you're not changing the license, off course :) )

No problem with that :)

@piotrtomiak is it ok for you? If it's OK, I will close this issue.

**Comment by piotrtomiak** [comment]
@angelozerr thanks! looks fine :)

**Comment by angelozerr** [comment]
Cool!
