### ISSUE TITLE
ES6: Map for .. of support

### ISSUE THREAD

**Issue by paulvi** [angelozerr/tern.java#328]
When following https://iojs.org/en/es6.html

### Which ES6 features ship with io.js by default (no runtime flag required)?

- Collections

     - Map

![image](https://cloud.githubusercontent.com/assets/1614482/10015228/aa47d77e-6151-11e5-8e1e-13b299753600.png)

is example from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map

**Comment by angelozerr** [comment]
What is the problem with this issue? If it is about errors validation, it's because of JSDT validator.

**Comment by paulvi** [comment]
Actually this example can't be run by node v4.1

```
D:\Workspaces\Enide-2015-7\ES6\map.js:4
for (var [key, value] of myMap) {
         ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3
```

**Comment by paulvi** [comment]
yes, removing `<nature>org.eclipse.wst.jsdt.core.jsNature</nature>` 

and setting in `.jshintrc`
	"esnext" : true, // Allow ES.next (ECMAScript 6) specific features such as `const` and `let`.


clears all

![image](https://cloud.githubusercontent.com/assets/1614482/10015400/85a8de9e-6152-11e5-81fc-14440a34bb63.png)

**Comment by angelozerr** [comment]
The Tern ES6 support is for completion, hyperlink (I must implement tern-lint for validation).

JSDT has 2 limitations (Validation + Syntax coloration) that I have explained here https://github.com/angelozerr/tern.java/wiki/Tern-&-ECMAScript6-support#jsdt-limitation and see https://gist.github.com/vrubezhny/18afdbf1194b59604c7d#file-wtp-jsdt-development-txt

I hope JSDT will improve that
