### ISSUE TITLE
[Tern Outline] Improve performance whith a big JavaScript files 

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/tern.java#335]
Tern Outline can freeze Eclipse when the outline tree UI is refreshed, I must study how to fix that:

 * refresh only the tree item which must be refreshed
 * support outline without searching type?

**Comment by paulvi** [comment]
Can UI refresh be after separate Job thread is finished.

i.e. not to do on main UI thread

**Comment by piotrtomiak** [comment]
There is just one UI thread in SWT. If you refresh whole huge tree, app will hang :)

**Comment by angelozerr** [comment]
> Can UI refresh be after separate Job thread is finished.

I have tried to do that, see:

https://github.com/angelozerr/tern.java/blob/master/eclipse/tern.eclipse.ide.ui/src/tern/eclipse/ide/internal/ui/views/TernContentOutlinePage.java#L107

But I'm not a big killer with Job and Thread. I have tested with big file like angular.js and Eclipse freezes -( Any contributions, ideas are welcome!

**Comment by paulvi** [comment]
- [ ] There should not be processing if the View is minimized.

- [ ] while there is performance problem do no immediately refresh with `redone = true;` It will make things worse.

https://github.com/angelozerr/tern.java/blob/master/eclipse/tern.eclipse.ide.ui/src/tern/eclipse/ide/internal/ui/views/TernContentOutlinePage.java#L83`

- [ ] use AtomicInt numberOfRefreshesToDo (+1 at entry, -1 at exit). This way you can get rid of `synchronized` (that can cause switch to other thread ). And also you can catch situation when there are many refresh requests coming, while refresh is going on. That would be suspicious situation (logic problem)

**Comment by angelozerr** [comment]
@paulvi Ia PR should be better, please.

@piotrtomiak is there any chance that you work on this issue if MyEclipse is interested with tern outline? I would like to improve it like ES6 support. thanks!

**Comment by piotrtomiak** [comment]
@angelozerr I will work on this. We are now integrating the newest version and performance is very important to us :) You should expect a commit this week.

**Comment by angelozerr** [comment]
@piotrtomiak great!

So I can spend my time to support tern outline with ES6 like class declaration , class expression, module imports, etc. I think I will have something this week.

As you are patching JSDT if I understand, you will able to use in the Outline View the Tern Outline because TernContentOutlinePage extends org.eclipse.ui.views.contentoutline.ContentOutlinePage.

**Comment by piotrtomiak** [comment]
Exactly :)

**Comment by angelozerr** [comment]
@piotrtomiak it seems the problem of freeze commes from when the tree is expanded. See https://github.com/angelozerr/tern.java/blob/master/eclipse/tern.eclipse.ide.ui/src/tern/eclipse/ide/internal/ui/views/TernContentOutlinePage.java#L117

Other project had this problem https://github.com/palantir/eclipse-typescript/issues/50

But JSDT have not this problem, perhaps it compute a delta kind to refresh only the tree node which is needed?

**Comment by mickaelistria** [comment]
As I'm working on refactoring Outline to make it more CNF/JSDT friendly, I've done a few things on this topic that might fix this issue.
Can you please provide steps to reproduce (what projects you have in your IDE while testng, which interesting settings were made, what files a open and what action does trigger the freeze) ?

**Comment by angelozerr** [comment]
> I've done a few things on this topic that might fix this issue.

Cool!

> Can you please provide steps to reproduce 

 * create a Simple Project
 * Convert to tern project
 * Check that "Outline is checked in the Tern -> Modules project properties
 * copy/paste a big JS file like angular.js in your project
 * Open Tern Outline View
 * The outline should be filled
 * Type some spaces, in angular.js and move the cursor and you will see that cursor will stop to move when tree.expandAll() is done.

**Comment by angelozerr** [comment]
Many thanks to @mickaelistria who have fixed this issue with https://github.com/angelozerr/tern.java/pull/348 and https://github.com/angelozerr/tern.java/pull/353
