### ISSUE TITLE
[ESLint] Allow absolute paths for eslint.json

### ISSUE THREAD

**Issue by neothemachine** [angelozerr/tern.java#342]
Since config files are [now](https://github.com/angelozerr/tern.java/issues/234#issuecomment-145439763) exchangeable it would be nice if it is possible to also put an absolute path for ESLint's json file. If I have several projects then I might not want to copy the same eslint.json into each project.

**Comment by angelozerr** [comment]
It looks like same feature than https://github.com/angelozerr/tern.java/issues/297 (but for JSHint).

**Comment by neothemachine** [comment]
True! Didn't see that. So there's demand, which is good :)

**Comment by angelozerr** [comment]
> So there's demand, which is good :)

If I understand your need. You wish to select an eslint.json from an another project (eg: commons-config). If you wish to do that I think you can do it by setting it the value at hand ../commons-config/eslint.json

**Comment by neothemachine** [comment]
Not another project, but any file on my system. I really like to put it 
an absolute path like /foo/bar/eslint.json (or the equivalent on Windows).

**Comment by angelozerr** [comment]
Ok I have improved the UI, now you can select eslint.json from project, workspace or file system.

![eslintconfig](https://cloud.githubusercontent.com/assets/1932211/10286253/2fa5735a-6b8d-11e5-8b6f-96a4806d44da.png)

I have added too an error messag ewhen fiel is not valid. Tell me if it works for you.

**Comment by neothemachine** [comment]
Looks good, I'll test it later. A suggestion to avoid any confusion: I 
would use the singular in "Use config file"

**Comment by neothemachine** [comment]
Works, thanks!

**Comment by angelozerr** [comment]
@neothemachine I use "Use config files" like WebSorms for JSHint https://www.jetbrains.com/webstorm/help/jshint.html.
