### ISSUE TITLE
Support easy debugging of tern.js from within running Eclipse

### ISSUE THREAD

**Issue by piotrtomiak** [angelozerr/tern.java#349]
I am continuing our discussion from here https://github.com/angelozerr/minimatch.java/pull/4#issuecomment-143226312

![shot_20151008_001](https://cloud.githubusercontent.com/assets/4244523/10370505/7b1bb3e0-6ddf-11e5-823f-02bfdddc8155.png)

So my idea is to add a field like on the screenshot and support Webclipse JS Debugger, but add a framework to provide other debuggers as well. I want to enclose all of this in the node.js core/ui plugins, so that there are no changes required to other plugins. There is no need for a per project settings. Each project will spawn as usual a new tern server, but in a debug mode. So far I did the UI and now going to dive deep into the core ;)

**Comment by angelozerr** [comment]
> So my idea is to add a field like on the screenshot and support Webclipse JS Debugger, but add a framework to provide other debuggers as well.

Yes it was my idea too! You mean an extension point to add a new debugger, is that? If it that it should be cool to provide an abstract class which does commons thing (like search a lanch, execute it and retrieve node.js port).

> There is no need for a per project settings.

Why? How it works if you have several tern projects in your workspace?

**Comment by piotrtomiak** [comment]
> You mean an extension point to add a new debugger, is that?

No, extension point is not needed. We can start debug session by just configuring appropriate launch config. That does not require any dependency between plugins and extension points. So in eclipse.nodejs.core there will be a single "configurer" for each type of debug session. Those configurers will turn on, if installation has appropriate launch config type and will display in the UI.

> Why? How it works if you have several tern projects in your workspace?

What happens right now, is that for each project a new tern server is started. The same will happen if debug mode is on, but all of those servers will start in debug mode.

**Comment by angelozerr** [comment]
> if installation has appropriate launch config type and will display in the UI.

It means that Launch of Webclipse should be customized with a given port like 1234 and Remote access of tern preferences must be setted to 1234 too. User must do 2 configurations, no? Or perhaps I miss something?

My idea with extension point is that the impl with Webclipse extension point is to :

 * create a Webclipse launch with a random port.
 * extension point return this random port
 * tern client use this random port.

> What happens right now, is that for each project a new tern server is started. 

It works like this today. A tern server hosts the whole files of the project. If we have one tern server for the all projects we will have conflict between files of different project for completion, etc.

**Comment by piotrtomiak** [comment]
> My idea with extension point is that the impl with Webclipse extension point is to :

Exactly, but Webclipse plugin do not have to be involved at all. Eclipse Nodejs plugin can create a Webclipse launch without using a single class from Webclipse. It can also find a free, random port. Thus it can setup a debug launch config and launch it.

> If we have one tern server for the all projects we will have conflict between files of different project for completion, etc.

Just like with java applications, there can be multiple debugging session with JS. So for each project a new tern server is started in debug mode.

**Comment by angelozerr** [comment]
So the idea is to debug the all tern project or not. The random port will work too.

Great idea @piotrtomiak !

**Comment by angelozerr** [comment]
@dgolovin @vrubezhny @paulvi I think you could be interested with this topic since you have or plan to develop a JS debugger.

**Comment by paulvi** [comment]
I am definitely interested.  
Users should have choice.  
Port should be from some range, not just random Integer.

Note, that Webclipse is currently not compatible with Nodeclipse version of Chrome Dev Tools.
https://www.genuitec.com/forums/topic/error-installing-into-enide-2015/

I don't have time to test Webclipse (at least this year), but I would love to give users this option, even though it is closed-source commercial.

**Comment by paulvi** [comment]
@piotrtomiak I am unable to login to comment on https://www.genuitec.com/forums/topic/error-installing-into-enide-2015/ (even after reseting password via link sent by email, it say account is not activated. That is one of example why users don't like non GitHub projects: you have to learn some other issue-tracker, and the like systems)

**Comment by piotrtomiak** [comment]
> I am definitely interested. Users should have choice. Port should be from some range, not just random Integer.

Please have a look at the PR (I've added more screenshots there). The setup is seamless, no need to set up any ports. It launches the tern process in the same way as Tern.java does normally, but additionally attaches a debugger. I've started to work with the extension to develop some additional features for Tern and it's really helping (hope you've @angelozerr tested it already). Right now, the biggest problem for accepting the PR is whether supported debuggers should be always listed or not (see https://github.com/angelozerr/tern.java/pull/351#discussion_r41715110)

>  I am unable to login to comment on 

@paulvi - thanks for your information, I'll take it up with our support team (you can always report such situations to support@genuitec.com). Anyway, your comment gave me an idea - maybe allowing for GitHub, Facebook or Google+ logins would simply the process? What do you think?

> I would love to give users this option, even though it is closed-source commercial.

Thanks! I think we could both work on getting this to work, though I guess most of the job will be on our (Genuitec) side. We are also interested into getting Webclipse to work with Nodeclipse, so I'll be looking into this in the near term.

**Comment by angelozerr** [comment]
> hope you've @angelozerr tested it already

No -( I must introduce tern.java at http://www.leclustr.org/agenda/eclipse-day-3 I will try your work next week.

**Comment by piotrtomiak** [comment]
Ok, so you still don't know how it speeds up tern code development :)

**Comment by angelozerr** [comment]
> Ok, so you still don't know how it speeds up tern code development :)

Yes, I have tested quicly Webclipse with ternjs and it works great:) I'm very exciting to test your PR, I would like just that everybody are agree with or without extension point.

**Comment by piotrtomiak** [comment]
Glad to hear that! :)

**Comment by piotrtomiak** [comment]
> I am unable to login to comment on https://www.genuitec.com/forums/topic/error-installing-into-enide-2015/

Paul, our support team has tried to locate your account, but was unable to find it. Could you please email support@genuitec.com with the details of email you have registered on our forum?

**Comment by paulvi** [comment]
> Anyway, your comment gave me an idea - maybe allowing for GitHub, Facebook or Google+ logins would simply the process? What do you think?

Nowadays, GitHub is like social network for developers. Google Code gave up. 

> email to support

doing right now

**Comment by angelozerr** [comment]
Close via PR https://github.com/angelozerr/tern.java/pull/351
