### ISSUE TITLE
check out on Windows - Filename too long

### ISSUE THREAD

**Issue by paulvi** [angelozerr/tern.java#35]
> D:\workspaces\Enide-Studio-2014-011\tern.java-CRLF>git checkout -f HEAD
> fatal: cannot create directory at 'eclipse/tern.eclipse.ide.server.nodejs.embed.linux.gtk.x86/nodejs/node-v0.10.22-linux-x86/lib/node_modules/npm/node_modules/request/node_modules/form-data/node_modules/combined-stream/node_modules/delayed-stream': Filename too long

FYI, on Windows 7 32bit

There were no such problem before on Windows.

**Comment by natasha544** [comment]
I had same problem then i use Long path tool.

**Comment by natasha544** [comment]
long path tool can be helpful. thanks

**Comment by angelozerr** [comment]
I don't understand you rproblem, today we use zip file.

**Comment by paulvi** [comment]
@natasha544 Please raise new issue

**Comment by AndrewJobel** [comment]
I recommend LongPathTool, Please try.
