### ISSUE TITLE
.jshintrc not reload, I have to restart Eclipse for the changes to be reload.

### ISSUE THREAD

**Issue by Rorkal** [angelozerr/tern.java#356]
Hi.

I found that .jshintrc is not reload on validation so when I change values inside the file (ex: 'maxlen'), there will be no change to validation until I restart Eclipse.
It's not blocking but can be troubling at first.

**Comment by angelozerr** [comment]
@Rorkal yes I know that, it's because this file is read once time when tern server is started. I will see if it can be improved. To stop the tern server you must activat eTern Console (project properties Tern Developement trace on console.)

I have th eintention to add this stop tern server inside Tern Outline.

**Comment by angelozerr** [comment]
Once https://opensagres.ci.cloudbees.com/job/tern.java/760/ will be finished you will able to reinstall it. Now you can change the .jshintrc without stopping the tern server.

**Comment by Rorkal** [comment]
Hi! 
Thanks for the quick fix!
Unfortunatly i did the update and i doesn't seems to work. I still need to restart Eclipse or stop tern server for the validation to work with the new configuration. :(

**Comment by angelozerr** [comment]
It should work:

 * perhaps you have not installed the last version (job was not finished when you have installed?)
 * when you change the .jshintrc, you need to type something in your editor to refresh the validation.

**Comment by Rorkal** [comment]
I'm using the last version.
After changing value from .jshintrc, i tried "Validate", "Clean project" and editing a source file to force validation. Nothing seems to work.

**Comment by angelozerr** [comment]
Is https://github.com/angelozerr/tern.java/blob/master/core/ternjs/node_modules/tern-jshint/jshint.js is the same than yours. You can find this folder in your ECLIPSE_HOME/plugins/ternjs*

**Comment by Rorkal** [comment]
Yes it's the last version.

**Comment by angelozerr** [comment]
I don't understand, please share your project.

**Comment by Rorkal** [comment]
I think it's something wrong with my eclipse configuration, 
i'm lauching eclipse with a CMD file : 
```
START %ECLIPSE_HOME%\eclipse.exe %* -vm %JAVA_HOME%\bin\javaw.exe -data %PROJECT_HOME%\workspace -configuration %PROJECT_HOME%\eclipseconf
```
Plugins are installed in the %PROJECT_HOME% folder but enabling trace shows me it uses %ECLIPSE_HOME%\plugins\ternjs_1.1.0.201510061208 wich is a previous version. I'll look into it.

Besides an other developers on the project has an unique plugin folder with 3 different versions of your plugin:
- ternjs_1.1.0.201510061208
- ternjs_1.1.0.201510140911
- ternjs_1.1.0.201510141008

and the trace shows that the plugin is alwa
ays using the old version (ternjs_1.1.0.201510061208)

I will look into it and let you know if I find where it comes from.

**Comment by Rorkal** [comment]
I found that the repository wasn't updated with the plugin update!

For anyone who experience the same problem: 
I had to go to "Window > Preferences" and to "JavaScript > Tern > Development > Repository" to add a new repository corresponding to the last version of ternjs.
