### ISSUE TITLE
tern 1.0.0 in eclipse has no preference->tern-menu

### ISSUE THREAD

**Issue by nimo23** [angelozerr/tern.java#357]
I have installed tern 1.0.0 in mars sr1 but menu-entry "preference->tern" is missing. Is this a bug?

**Comment by jabby** [comment]
Maybe you have jsdt in your Eclipse. Can you verify if you have an entry in Preferences > JavaScript ?

**Comment by nimo23** [comment]
I have mars sr1 jee-package and the entry "Preferences > JavaScript" is still there. But tern-menu is missing on both sides "project->properties" and "eclipse->settings".

**Comment by nimo23** [comment]
Should I try to upgrade to 1.1.0 Snapshot? I guess, then menu-entries are visible. I had such a problem a few month ago and had solved that by updating to 1.1.0 Snapshot. But then, the existing dependencies to other plugins (nodeclipse and the like) could make conflicts when not using tern 1.0.0. Am I right?

**Comment by nimo23** [comment]
"Terns Code Completion" in javascript files are working without errors. However, "tern menu entries" are missing in "preferences".

**Comment by jabby** [comment]
@nimo23 I tried on my computer with Mars 4.5 and tern 1.0.0 and I have no problem. 
I also tried with Mars sr1 and tern 1.0.0. I don't understand what happens. 

Can you provide your OS versio and the exat version number for tern ? is it 1.0.0.201508302102 ?

For problems between nodeclipse, jboss tools and tern 1.1.0, I can't answer. Maybe @paulvi or @mickaelistria can help you.

**Comment by nimo23** [comment]
![screenshot at okt 14 23-14-51](https://cloud.githubusercontent.com/assets/3045549/10497390/d086d810-72c5-11e5-8d47-d4868438b7d8.png)


![screenshot at okt 14 23-15-46](https://cloud.githubusercontent.com/assets/3045549/10497392/d6c2e642-72c5-11e5-9748-bec52f573104.png)

**Comment by nimo23** [comment]
For problems between nodeclipse, jboss tools and tern 1.1.0, I can't answer.

If I upgrade to snapshot 1.1.0, then all the dependent plugins need to rely on 1.1.0 as after upgrading 1.0.0 is not there anymore. Am I right?

**Comment by paulvi** [comment]
Isn't Tern under JavaScript now?

![image](https://cloud.githubusercontent.com/assets/1614482/10503711/610eee1c-732b-11e5-9502-7f0862f0b02f.png)


@nimo23 There's ongoing discussion, one of them is https://github.com/angelozerr/tern.java/issues/350

**Comment by paulvi** [comment]
@nimo23 

> If I upgrade to snapshot 1.1.0, then all the dependent plugins need to rely on 1.1.0 as after upgrading, version 1.0.0 is not there anymore. Am I right?

1.0.0 is released, 
1.1 is SNAPSHOT, CI build, but basically it is to be as stable as released.

**Comment by angelozerr** [comment]
@nimo23 I don't know why you have a problem with preferences with 1.0.0, but I have no time to investigate your problem because I prefer taking my time to continue 1.1.0.

I don't know too if you will have problem if you install 1.1.0 and you use Nodeclipse or JBoss Tools.

The test that you do, is too type "Tern" inside the "type filter text" to know if Tern appears. As @paulvi said, in 1.1.0 Tern is hosted inside JavaScript node for preferences and project properties (only if your project has JSDT nature). See https://github.com/angelozerr/tern.java/wiki/New-and-Noteworthy-1.1.0#tern-property-pages

**Comment by nimo23** [comment]
@angelozerr yes, it s good to invest your time to 1.1.0 instead of 1.0.0. I updatet to snapshot 1.1.0 and the menu entries are visible now.
