### ISSUE TITLE
Preference page for Node.js server settings broken

### ISSUE THREAD

**Issue by phaensgen** [angelozerr/tern.java#360]
Hi,
for some reason the Node.js preference page (global preferences ->JavaScript -> Tern -> Server -> Node.js) is blocked in my Eclipse installation. I am using the latest snapshot release.
The OK button is always disabled and nothing can be changed. When leaving the page, an error message like "The currently displayed page contains invalid values." is shown, no further explanations.
I know it used to work before, maybe this has to do with some changes that were done in the last weeks in this area?
I would like to use remote access, but unfortunately this is not possible right now...

**Comment by angelozerr** [comment]
@phaensgen I know this problem. I'm working to replace "tern server file" with "tern repository". I try to commit my work ASAP.

**Comment by angelozerr** [comment]
@phaensgen please reinstall 1.1.0-SNAPSHOT, (hope) problem should be fixed.

**Comment by phaensgen** [comment]
Yes, after updating to the latest build it works again. Thank you!

**Comment by angelozerr** [comment]
That's cool, I close this issue.
