### ISSUE TITLE
Use tern repository (instead of tern server file) in NodeJS preferences

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/tern.java#362]

**Comment by angelozerr** [comment]
@piotrtomiak I have done a big refactoring to support tern repository inside Eclipse project. I have modified the UI of Node.js preference page. Hope you will like it. (the Add button is not implemented for the moment).

Hope there will have not a lot of bug and you will like it.

**Comment by piotrtomiak** [comment]
@angelozerr Great. I will have a look at it soon :)

**Comment by angelozerr** [comment]
@piotrtomiak had you hav etime to test this issue? Can I close this issue?

**Comment by piotrtomiak** [comment]
@angelozerr sorry, I got distracted and forgot to check. I think you can close it, if there are any problems, I'll just open a new one

**Comment by angelozerr** [comment]
Ok thanks, I close the issue.
