### ISSUE TITLE
[JSDoc] Support for Chinese character

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/tern.java#364]
This issue comes from https://github.com/angelozerr/tern-jshint/issues/2. Here a JavaScript snippet with Chinese comment:

```javascript
var test_obj = {
    /**
     * English: this is a test function<br/>
     * Chinese: 这是一个测试函数
     */
    test_func: function() {
    }
}
```

The Hover, Completion, shows "??????" instead of showing " 这是一个测试函数".

Problem comes from the Http post client (from tern.java) which doesn't encode the request/response. To fix problem, we need to set encoding like this : 

 * request: 

```java
httpPost.setEntity(new StringEntity(doc.toString(), "UTF-8"));
```

 (see https://github.com/angelozerr/tern.java/blob/master/core/tern.server.nodejs/src/tern/server/nodejs/NodejsTernHelper.java#L124)

 * response:

```java
JsonObject response = JsonObject	.readFrom(new InputStreamReader(in, "UTF-8"));
```
(see https://github.com/angelozerr/tern.java/blob/master/core/tern.server.nodejs/src/tern/server/nodejs/NodejsTernHelper.java#L90)

But I think we should use the tect editor encoding instead of using hard coded encoding.

As it's a important changes, I will not do that in 1.1.0 which will be released soon.

@mickaelistria @vrubezhny @dgolovin @maxandersen @PaulVI @fbricon @piotrtomiak it's a very important changes, so are you OK I force the encoding of http request/response from the text editor encoding?

**Comment by mickaelistria** [comment]
I agree it seems more consistent to use the text editor encoding (usually set to UTF-8) for that operation rather than relying on the JVM encoding (usually set to Cp-1215 or other on Windows). I believe it's not such a critical change, although a very useful one, so IMO if it can fit in 1.1.0, it's a good candidate to get in.

**Comment by angelozerr** [comment]
Thanks @mickaelistria for your answer.

> so IMO if it can fit in 1.1.0

It will not possible since @pascalleclercq has doen yesterday the 1.1.0 release.

**Comment by hawkxu** [comment]
hope it will coming soon in 1.2.0-SNAPSHOT, thanks!

**Comment by piotrtomiak** [comment]
@angelozerr - that really sounds like a really good change.

**Comment by mickaelistria** [comment]
Actually, doesn't the Tern server enforce an encoding? ie, would relying on the editor encoding work for Tern, or does it enforce usage of UTF-8 so the strings should be re-encoded when they're not UTF-8 ?

**Comment by angelozerr** [comment]
> Actually, doesn't the Tern server enforce an encoding?

@mickaelistria very good question!

Indeed, tern uses UTF-8 https://github.com/ternjs/tern/search?utf8=%E2%9C%93&q=utf8 so I will force the request/response to UTF-8. I don't know if it will causes problem if the IFile has an charset different from UTF-8.

**Comment by mickaelistria** [comment]
So you should enforce UTF-8 in your request/response code above.
What you could try as a primary step is to check if text editor/IFile encoding are UTF-8. If they're, then great, you can pass the string directly with `doc.toString()`, else you'll have to pass a `new String(doc.toString(), "UTF-8")`

**Comment by angelozerr** [comment]
@hawkxu please install http://oss.opensagres.fr/tern.repository/1.2.0-SNAPSHOT/ Chinese character should be fixed (I hope).

@mickaelistria I have a little played with encoding and it seems I must set every time the request/response to UTF-8 even if the IFile has not UTF-8.

**Comment by mickaelistria** [comment]
Yes, that makes sense. I guess the StringEntity automatically re-encode the String to UTF-8 anyway, so my suggestion above seems useless.

**Comment by hawkxu** [comment]
Yes, now the hover display Chinese characters instead of ????, that's great, thanks very much.

**Comment by paulvi** [comment]
To summarize: whatever encoding is used in file, when transmitting to and from tern server it should be in UTF-8. Or simply "use UTF-8 everywhere"

**Comment by angelozerr** [comment]
Thanks everybody for your feedback. I close this issue.
