### ISSUE TITLE
Tern Outline display many anonymous

### ISSUE THREAD

**Issue by hawkxu** [angelozerr/tern.java#366]
As you can see, the Tern Outline display many anonymous item.
<ul>
<li>test_func in test_obj</li>
<li>the test_class1 dispeared</li>
<li>the test_class2 members</li>
<li>the test_class3</li>
</ul>
I am a newbe of tern.java (also javascript), I do not know if this is my fault.

thanks for any help!

[test.js.txt](https://github.com/angelozerr/tern.java/files/31490/test.js.txt)
![anonymous](https://cloud.githubusercontent.com/assets/9413820/11081761/8a65f956-885a-11e5-8bd0-848dc4e08612.png)

```javascript
var test_obj = {
    test_func: function() {
    }
};


var test_class1 = function() {
  this.public_func = private_func;
  
  function private_func() {
    
  }
};

var test_class2;
(function() {
  test_class2 = function() {
    function private_function() {
    }
  };
  
  test_class2.prototype = {
      proto_func: function() {
      }
  };
})();

var test_obj3;
(function() {
  var test_class3 = function() {
    function private_function() {
    }
  }
  
  test_class3.prototype = {
      proto_func: function() {
      }
  };
  test_obj3 = new test_class3();  
})();
```

**Comment by angelozerr** [comment]
> I am a newbe of tern.java (also javascript), I do not know if this is my fault.

Tern Outline is a new feature, so there are bugs, that's sure. I will study your issue when I will find time.

**Comment by hawkxu** [comment]
The Tern Outline can display and locate PRIVATE members, that's cool, hope it can be more useful, thanks!

**Comment by boniatillo-com** [comment]
@angelozerr I opened (https://github.com/ternjs/tern/issues/692) an issue in the tern repo about to get the AST with the type information.

I think with a query like that we can implement much better tools (like the outline) but in the client side (with Java).  For example, for me it is more easy to hack a Java code in your tern.java than a JavaScript code running in the tern plugins space.

I don't know if it is too difficult to write an ast plugin or if it already exist.

**Comment by angelozerr** [comment]
> @angelozerr I opened (ternjs/tern#692) an issue in the tern repo about to get the AST with the type information.

Yes I have seen that, but I think the answer will be "write a plugin for that".

> I don't know if it is too difficult to write an ast plugin or if it already exist.

If you see https://github.com/angelozerr/tern-outline/blob/master/outline.js#L188, you have the acorn AST which follows the [Mozilla Parser API](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/Parser_API)

I could send this AST for outline, but for performance reason. If I did that, it means that 

 * the AST JSON that I must return is more big than my JSON outline
 * with Java code, I must loop for the big JSON to build the outline

So I prefer, build a little JSON on the server side for the outline. 

Please note that you can use demos of outline https://github.com/angelozerr/tern-outline/tree/master/demos and debug the tern-outline with Chrome.

**Comment by boniatillo-com** [comment]
Yes I see... I should start learning the tern plugin API. Thanks.

**Comment by angelozerr** [comment]
It's not pefect, but here the result:

![a](https://cloud.githubusercontent.com/assets/1932211/11573661/b87aab8e-9a07-11e5-9a4a-a53fa7bd48ea.png)
