### ISSUE TITLE
Apply and Restore Defaults buttons do not work on main Tern property page (in project properties)

### ISSUE THREAD

**Issue by michal-grzejszczak** [angelozerr/tern.java#368]
The problem is with `WorkingCopy`, that is being `clear`ed on `commit`. If someone clicks `Apply`, working copy state will become desynchronized with property page controls, which leads to erratic behavior.

Is far as I can tell there is no support for either of these buttons, so it would be best to disable them for now. Calling `noDefaultAndApplyButton()` either in `createContents` or in constructor of `TernMainPropertyPage` will remove them from the page.

**Comment by angelozerr** [comment]
Thanks for the suggestion! Next time, I think you could create a PR for that.
