### ISSUE TITLE
Issue at validation with tern-eslint.

### ISSUE THREAD

**Issue by Xenope** [angelozerr/tern.java#369]
Hello, i think i might have an issue on validating js using eslint. I'm changing rules to make it appear as a warning but all I get is errors all over my js files.

Here is an example : 

I'm using the default conf file provided by eslint : 
![image](https://cloud.githubusercontent.com/assets/15614284/11275086/36cd8b3c-8edc-11e5-9336-14227b20fbde.png)
In this file I changed this rule to make it a warning when there is an unused var:

![image](https://cloud.githubusercontent.com/assets/15614284/11275119/661993f4-8edc-11e5-85ec-c0b797c32932.png)

In eclipse nothing changed, it steal provides me an error :
![image](https://cloud.githubusercontent.com/assets/15614284/11275331/7bdd7182-8edd-11e5-9c77-ba3467caea1f.png)

When executing eslint in the command line, it shows the good behavior :

![image](https://cloud.githubusercontent.com/assets/15614284/11275248/0937c0ce-8edd-11e5-868c-dee3192a2715.png)

Any thoughts about that?

**Comment by angelozerr** [comment]
It's because, tern-eslint is not able to reload config when eslint.json changes. It should be improved (like  tern-jshint which is able to do that).

So for the moment, you must stop your tern serevr at hand (click on stop button of the tern console) and retype soem content in yoru JS editor to reexcute the validation.

**Comment by Xenope** [comment]
thanks for the quick response.

I've already tried that, unfortunately it didn't work, still have the issue.

**Comment by angelozerr** [comment]
Could you share your project please.

> (tiens je suis français aussi ;))

:)

**Comment by Xenope** [comment]
here it is.

It is based on the aurelia skeleton app. The file i showed you is app.js, with not much in it, just that unused import showing an error. I assume you already have eslint whith the conf file, just modify the line I showed you.

**Comment by Xenope** [comment]
is it posible to reopen?

**Comment by angelozerr** [comment]
@Xenope I don't know aurelia and I would liek to have the sam econtext than you, so please share your project.

**Comment by Xenope** [comment]
I just found out that it doesn't overwrite the defaultconfig specified in eslint.js in the tern-eslint folder.
If I edit this file and change "no-unused-vars": to 1 it does change from error to warning in eclipse.

**Comment by Xenope** [comment]
I made some debug and see  that it loads my custom file but then in the config.js of eslint my rules are overwritte by the following line : 

   // Step 6: Merge in command line rules
    if (this.options.rules) {
        debug("Merging command line rules" + this.options.rules);
        config = util.mergeConfigs(config, { rules: this.options.rules });
    }

this.options.rules corresponds to the defaultConfig.rules defined in the eslint.js file.
If i comment it my customfile is loaded with my custom rules.

**Comment by angelozerr** [comment]
Thanks @Xenope for your feedback, I will see that.

**Comment by angelozerr** [comment]
@Xenope I have improved tern-eslint:

 * I don't use default config, so your problem should disappear
 * you can update the eslint.json without stopping tern server (you must just revalidate at hand your JS editor after changing your eslint.json).

Tell me if it works for you.

**Comment by Xenope** [comment]
Well i can sucssefully say that it works fine now :). Thanks!!

**Comment by Saurabh06** [comment]
I want to use my made eslint config file instead of default eslint file for javascript validation in my tern protractor project. Can you please help me out how to use my config file instead of default eslint in eclipse for validation.

**Comment by Xenope** [comment]
I simply put it like this
![selection_153](https://cloud.githubusercontent.com/assets/15614284/14953946/a6d36582-106e-11e6-8d7f-d405ae6a724c.png)
and that's it.
