### ISSUE TITLE
Package `tern.server.protocol.push` exported but not existent

### ISSUE THREAD

**Issue by boniatillo-com** [angelozerr/tern.java#371]
I cloned this repo and imported to Eclipse but I get this error in the `tern.core` manifest file:

`Package 'tern.server.protocol.push' does not exist in this plug-in`

I confirmed that package does not exist on the master branch.

**Comment by angelozerr** [comment]
@boniatillo-com sorry with this error. I'm implementing WebSocket with tern node.js (to push some message from tern server to the client (Eclipse) to for instance refresh Angular Explorer as soon as modules changes, see https://github.com/angelozerr/tern.java/issues/363)

I have commited my work, but it's not finished, hope you will have not problem with my commit.

**Comment by boniatillo-com** [comment]
It is fine, I just commented that import. Thanks.

**Comment by angelozerr** [comment]
Ok, I close this issue.
