### ISSUE TITLE
How to get the jsdoc of a function parameter

### ISSUE THREAD

**Issue by boniatillo-com** [angelozerr/tern.java#375]
The parameter information given in the `tern.server.protocol.completions.Parameter` does not contain any method to get the parameter doc.

Actually I see no parameter doc in the screenshots shown in the Tern Eclipse IDE wiki:

![Tern Eclipse IDE](https://github.com/angelozerr/tern.java/wiki/images/EclipseIDE_TernjQueryCompletion.png)

**Comment by boniatillo-com** [comment]
Actually, I do not see a method to get the doc of the function return neither.

**Comment by angelozerr** [comment]
It's because ternjs doesn't support doc for parameter. The JSON Type Definition supports doc only for function but not for parameter.

**Comment by boniatillo-com** [comment]
Ok, I will open an issue in ternjs then. Thanks.

**Comment by boniatillo-com** [comment]
I did a work around, maybe someone can take advantage of it too. What I am doing is generating a definition file with no jsdoc at all, just with the API information, so each function, property etc will have as "!doc" the qualified name of the member, for example, `MyProduct.MyClass.mymethod`. So I can use tern for completions but I get all the metadata from the json file generated by the jsdoc tool.
