### ISSUE TITLE
Missing `documentation` query.

### ISSUE THREAD

**Issue by boniatillo-com** [angelozerr/tern.java#378]
I do not see any implementation for the `documentation` query.

In the meantime I am doing this:

```
TernQuery query = new TernQuery("documentation");
query.set("file", filename);
query.set("end", Integer.valueOf(pos));
```

**Comment by angelozerr** [comment]
Yes you are right, it misses this tern query because I don't use it. If you need it, please create a PR to add it. Thanks!

**Comment by boniatillo-com** [comment]
My swing editor is going very well, as soon as I finish the preview version I will get the time to contribute back to tern.java, count with that. 

Ok I am testing how you are giving hover feedback and I see you are requesting a `type` query, which is actually a more suitable query because it returns the doc but also the name of the expression in question. So I will do the same on my editor. I don't know if the `documentation` query has any advantage but right now I do not see any.

**Comment by boniatillo-com** [comment]
I close this the `type` query gives more information than `documentation` so I see no reason for use the last.
