### ISSUE TITLE
The tern project is not "updated" after change it

### ISSUE THREAD

**Issue by boniatillo-com** [angelozerr/tern.java#380]
I am using the `core` classes (in swing application) and I created the tern project in this way:

```
_ternProject = TernResourcesManager.getTernProject(projectDir.toFile());
_ternProject.setRepository(repository);
_ternProject.addPlugin(TernPlugin.jshint);

if (!_ternProject.getTernProjectFile().exists()) {
	_ternProject.save();
}
```

It adds the jshint plugin, but it happens to me that if I modify the .tern-project to configure jshint options, then those changes are not taken in count unless I restart the application.

It is like if the project loads the first time but cannot be modified in runtime.

Actually, if just delete all plugins from the `.tern-project` file or delete the file, my editor keeps working as usual. It works like if tern.java creates a cache of the `.tern-project`.

**Comment by boniatillo-com** [comment]
Well, thinking more... I guess when the tern server is created, it loads the `.tern-project` and keep it on memory. So the solution is to restart the server when that file is modified. It can be expensive, but is better than restart the whole editor. In the case of `jshint`, the better is to reference an external `.jshintrc` file, in that way you can tune jshint without restart the tern server.

**Comment by angelozerr** [comment]
@boniatillo-com you have everything understood. ternjs uses .tern-project on start server so you cannot update it after. The tern-jshint is able to refresh jshintrc if it changes on runtime.
