### ISSUE TITLE
jshint breaks the server connection

### ISSUE THREAD

**Issue by boniatillo-com** [angelozerr/tern.java#381]
When the `.jshintrc` has an invalid format, the jshint plugin breaks the server connection and I do not find  a way to avoid this. I think we need a way to catch that plugin exception in the server an send back the error to the client as usual, via `IResponseHandler.onError()`.

This is the error:

```
[31mERROR[0m: Can't parse config file: C:/Users/arian/Documents/Test/test_rayo/.jshintrc
Error:SyntaxError: Unexpected token k

Tern error#jshint with 27ms: 
java.net.SocketException: Connection reset
```

**Comment by angelozerr** [comment]
The .jshintrc is loaded when tern server is started. So if it is not valid, tern server cannot be started. Is it a problem? What is your suggestion?

**Comment by boniatillo-com** [comment]
Yes it is  a problem because it is a file that a user needs to change from time to time. I think the jshint plugin, at least, should catch any syntax error, print a message error and fallback to a default jshint configuration. I will look more into the plugin.

**Comment by boniatillo-com** [comment]
This is the same issue but in Atom:

https://github.com/sindresorhus/atom-jshint/issues/21

**Comment by boniatillo-com** [comment]
Problem solved.

The cli.js file exits if it cannot parse the config file. So what I did was to modify the `loadConfig` method and replace all `exports.exit(1)` by `return {};`

Maybe other option is to avoid using `cli` and load the config in the plugin.

**Comment by angelozerr** [comment]
@boniatillo-com  could you create a PR for tern-jshint please. Thanks!

**Comment by boniatillo-com** [comment]
I never wrote a single line of `nodejs`. I was trying to load the config in the plugin and not in the `cli` but I got lot of errors, for example I don't know how to inclue `shelljs` etc..

**Comment by boniatillo-com** [comment]
How can I include `shelljs` in the plugin? To do `var shjs = require("shelljs")` does not work.

**Comment by angelozerr** [comment]
Ok @boniatillo-com I will do that (you must add shelljs in package.json and do npm install to download shelljs inside node_modules).

**Comment by angelozerr** [comment]
@boniatillo-com don't loose your time with this problem. I will study it. I have an idea with https://nodejs.org/docs/latest/api/fs.html#fs_fs_watch_filename_options_listener to observe changes of a file. I would like to use to observe changes of .jshintrc to update it (instead of read every time the last mtime of teh file to know if it must be updated). So I could use watch too to check if jshintrc is valid or not.

**Comment by boniatillo-com** [comment]
Thanks very much @angelozerr 
I have to get some time to learn nodejs :(

**Comment by angelozerr** [comment]
@boniatillo-com please update tern.java, it should work. Now when you have an error with .jshintrc, it add an error in your JS file.

**Comment by angelozerr** [comment]
@boniatillo-com  could you tell me if it works for you? Thanks

**Comment by boniatillo-com** [comment]
Let me check.

**Comment by angelozerr** [comment]
@boniatillo-com can I close this issue?

**Comment by boniatillo-com** [comment]
yes please thanks

**Comment by angelozerr** [comment]
Thanks @boniatillo-com !
