### ISSUE TITLE
ES6 Validation & Auto-Complete

### ISSUE THREAD

**Issue by Knight-Yoshi** [angelozerr/tern.java#383]
I'm having issues setting up validation via Tern with ESLint. I disabled the internal parsing as shown, http://tools.jboss.org/documentation/whatsnew/jbosstools/4.3.0.Final.html#javascript-development-tools-improvements, and I enabled ESLint. In the project properties javascript > Tern > Validation > ESLint I specified the .eslintrc config file to use (also tried eslint.json).

I can run ESLint from the command line and it gives me all the nice errors to fix, but I don't know why it's not work in Eclipse via Tern. Also I enabled the jQ library, but it's not giving me auto-complete either. I'm not sure if there's some other configuration I'm missing for Tern or not.

**Comment by angelozerr** [comment]
At first I suggest you that you install tern.java 1.2.0-SNAPSHOT which improves eslint validation.

f you have again problem, please share your project (with github).

**Comment by angelozerr** [comment]
None answer, I close this issue.

**Comment by CharlyRipp** [comment]
I found that it expects only the rules in the configuration.
Instead of:
    {
        "env": { ... },
        "extends": "eslint:recommended",
        "parserOptions": { ... },
        "rules": {
            "no-trailing-spaces" : "error"
        }
    }

It's just looking for:
    {
        "no-trailing-spaces" : "error"
    }

**Comment by angelozerr** [comment]
@CharlyRipp please create a new issue with more info. I don't know very well ESLint.
