### ISSUE TITLE
The API

### ISSUE THREAD

**Issue by HaiboLee** [angelozerr/tern.java#385]
hi.I hope I can in accordance with API hints I want to come out,
do you have any idea,or where can setting.
.(I don’t want the lib’s ionic.js or jquery.js appear in the API hint’s,if my project have the js file ,it always appear)

**Comment by angelozerr** [comment]
I'm sorry I don't understand your issue?

**Comment by HaiboLee** [comment]
i send you email ,can you see the picture?

**Comment by angelozerr** [comment]
Please read https://github.com/angelozerr/tern.java/wiki/New-and-Noteworthy-1.0.0#includeexclude-tern-script-paths

**Comment by HaiboLee** [comment]
thank you very much. this is i need. sorry my English is not very good ^.^

**Comment by angelozerr** [comment]
@midzelis I tell me why you have forked tern.java with several changes? Have you the intention to contribute to tern.java?

**Comment by midzelis** [comment]
Yeah. I'm working on a ternjs plugin, and ran into a few issues in tern.java/eclipse plugin. I would love to contribute back the changes I'm making. Right now its still a work-in-progress. When its ready to go, I'll squash my git changes and submit a pull request.

**Comment by angelozerr** [comment]
> Yeah. I'm working on a ternjs plugin, and ran into a few issues in tern.java/eclipse plugin. I would love to contribute back the changes I'm making. Right now its still a work-in-progress. When its ready to go, I'll squash my git changes and submit a pull request.

It's a great news! IMHO I think you should create a GitHub project for tern-auraframework and if you are agree, I can host it inside tern.java. What do you think about that?
