### ISSUE TITLE
Tern Plugin for Grunt

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/tern.java#39]
Create Tern Plugin for Grunt by using : 

 * tern grunt plugin : https://github.com/angelozerr/tern-grunt
 * Grunt Eclipse https://github.com/angelozerr/grunt-eclipse which provide an Eclipse View with tasks in a tree.

**Comment by angelozerr** [comment]
I'm a newbee with grunt, @paulvi @ar2112 @jabby I'm developping a View which shows the whole grunt tasks from the Gruntfile.js (today I can display list of tasks from grunt.registerTask) but it seems that grunt.initConfig is used to register tasks, could you tell me (and give me sample) of tasks to display in a tree (after that we could execute it by double clicking) from a Gruntfile.js

Thanks!

**Comment by jabby** [comment]
I don't know how to represent in tree all grunt tasks. 

You can find an example here https://github.com/jabby/sample-4-angularjs-eclipse/blob/master/Gruntfile.js It's a Gruntfile.js generated by a yeoman generator. There are useful tasks like [serve](https://github.com/jabby/sample-4-angularjs-eclipse/blob/master/Gruntfile.js#L391), [server](https://github.com/jabby/sample-4-angularjs-eclipse/blob/master/Gruntfile.js#L406), [test](https://github.com/jabby/sample-4-angularjs-eclipse/blob/master/Gruntfile.js#L411), [build](https://github.com/jabby/sample-4-angularjs-eclipse/blob/master/Gruntfile.js#L419) and [default](https://github.com/jabby/sample-4-angularjs-eclipse/blob/master/Gruntfile.js#L436).

To call a task, you just need to write 
```javascript
grunt taskname
```
Theses tasks use other tasks which are defined in grunt.initConfig or tasks defined by grunt.registerTask. 

For taks defined in grunt.initConfig, you can look at [clean](https://github.com/jabby/sample-4-angularjs-eclipse/blob/master/Gruntfile.js#L134). It defines 2 tasks, clean:dist and clean:server clean:server is used [here](https://github.com/jabby/sample-4-angularjs-eclipse/blob/master/Gruntfile.js#L397) and clean:dist is used [here](https://github.com/jabby/sample-4-angularjs-eclipse/blob/master/Gruntfile.js#L420)

**Comment by angelozerr** [comment]
Many thank's @jabby it was exactly information that I need.

When I will finish my idea, are you OK to test https://github.com/angelozerr/grunt-eclipse (not available for the moment)

**Comment by paulvi** [comment]
grunt takes a lot of ideas from Gradle http://gradle.org/ (that also takes a lot from Maven and Ant)

Take a look at how it is implemented in Gradle integration https://github.com/spring-projects/eclipse-integration-gradle

**Comment by angelozerr** [comment]
Many thank's @paulvi for your helpful info!

**Comment by jabby** [comment]
@angelozerr Yes I will test your grunt-eclipse plugin. Send me an email when it is available or ping me in this issue.

**Comment by ar2112** [comment]
@angelozerr <https://github.com/angelozerr> I am interested in testing this
plugin whenever you are ready, thanks for the info!

**Comment by angelozerr** [comment]
@jabby @ar2112 @paulvi here a screenshot for Grunt View : 

![grunteclipse](https://cloud.githubusercontent.com/assets/1932211/6924331/1f0eef7e-d7d8-11e4-9aed-2c68c57c9aed.png)

What do you think?

**Comment by angelozerr** [comment]
@paulvi @ar2112 @jabby you can start playing with see https://github.com/angelozerr/jsbuild-eclipse

It supports Grunt and Gulp. Please read https://github.com/angelozerr/jsbuild-eclipse/wiki/Getting-Started

If you wish to have some new features for grunt, gulp. Please create issues at https://github.com/angelozerr/jsbuild-eclipse/issues
