### ISSUE TITLE
Eclipse tern. Jshint check HTML in the javascript when there will be a mistake

### ISSUE THREAD

**Issue by HaiboLee** [angelozerr/tern.java#391]
![image](https://cloud.githubusercontent.com/assets/16329338/12537038/64ed2174-c2f0-11e5-9377-ce6c64490b99.png)
Sometimes, sometimes not, there is a solution?

**Comment by angelozerr** [comment]
> Sometimes, sometimes not,

What do you mean? Please explain more your problem and please share your project in order to I can test quickly your problem.

**Comment by HaiboLee** [comment]
![image](https://cloud.githubusercontent.com/assets/16329338/12537231/d54e499e-c2f4-11e5-8e46-47c0ebc964a3.png)
![2016-01-24](https://cloud.githubusercontent.com/assets/16329338/12537239/e8abe96a-c2f4-11e5-88f6-33bf2fa1b377.png)
i want use the jshint module to check HTML in the javascript

**Comment by angelozerr** [comment]
If I understand your problem, you have marker error on the first line, although you should have none error?

If it that, try to validate your HTML file (select your HTML file, open the contextual menu and do Validate).

It's perhaps the same problem than https://github.com/angelozerr/tern.java/issues/374

**Comment by HaiboLee** [comment]
I don't think that 374 is the same mistake, I use jshint, when I no javascript code in the HTML file is not wrong, only using javascript code in the HTML in this problem,I think it's jshint problem

**Comment by HaiboLee** [comment]
I don't think this is the same problem with #374, because the tip is jshint mistakes, not HTML. I suppose jshint in identifying errors in HTML file

**Comment by HaiboLee** [comment]
This error is not, when you create a new HTML is not, when you close the editor and then open and use the validate may appear

**Comment by angelozerr** [comment]
@HaiboLee I have fixed the problem. It was when you do Validate at hand. When https://opensagres.ci.cloudbees.com/job/tern.java/853/ will be finished, you will able to install 1.2.0-SNAPSHOT

**Comment by HaiboLee** [comment]
thanks very much,it work now

**Comment by HaiboLee** [comment]
hi, @angelozerr First of all thank you very much to solve my problem, but I found that if you have any HTML files in your project and js files, when you have to validate the whole project, HTML will appear in the error, the folder is too. As a project or folder only HTML or separately to validate HTML is there won't be wrong, I think it might be a bug

**Comment by angelozerr** [comment]
Problem should be fixed. Please reinstall 1.2.0-SNAPSHOT when job https://opensagres.ci.cloudbees.com/job/tern.java/858/ will be finished.
