### ISSUE TITLE
TernException occures when trying to open hiperlink in JSP.

### ISSUE THREAD

**Issue by vrubezhny** [angelozerr/tern.java#392]
The issue is reproducible in JSP 1.2 files (JBDS 9.1.0.Beta2 + Tern.java + AngularJS-eclipse). 

Steps to reproduce:

1. Create JSF 1.2 project
2. Open inputUserName.jsp in VPE
3. Hover over <%@ taglib uri="http://java.sun.com/jsf/core"
4. Press Ctrl
ERROR:
{noformat}
tern.TernException: TernError: No type found at the given position.
	at tern.server.DefaultResponseHandler.getData(DefaultResponseHandler.java:45)
	at tern.server.protocol.TernResultsProcessorsFactory.makeRequestAndProcess(TernResultsProcessorsFactory.java:43)
	at tern.eclipse.ide.internal.core.resources.IDETernServerAsyncReqProcessor.run(IDETernServerAsyncReqProcessor.java:104)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: tern.TernException: TernError: No type found at the given position.
	at tern.server.nodejs.NodejsTernHelper.makeRequest(NodejsTernHelper.java:86)
	at tern.server.nodejs.NodejsTernServer.makeRequest(NodejsTernServer.java:163)
	at tern.server.nodejs.NodejsTernServer.request(NodejsTernServer.java:127)
	at tern.server.protocol.TernResultsProcessorsFactory.makeRequestAndProcess(TernResultsProcessorsFactory.java:42)
	... 2 more
{noformat}

Please, see https://issues.jboss.org/browse/JBIDE-21580 for more info.

**Comment by angelozerr** [comment]
@vrubezhny this error occurs every time that you try to open an hyerlink inside js content. Ex try to do Ctrl+Click on 'function'.

This error is thrown by ternjs. It's not a critical error. I have ignored this error when it occurs and Error Log View should not contains this error. Tell me if it was the problem and if it fixes your https://issues.jboss.org/browse/JBIDE-21580

**Comment by vrubezhny** [comment]
Am I correct in that it's like an informational message (like 'tern could not find any type at this position')?

@angelozerr  if it's not an error (a normal situation) it just should not being reported.

Any error/warning message reported to the Error Log disturbs a user - so it it's a normal situation and not an error - it's better not to report it at all.

Of course, the real errors/warnings still have to be reported.

**Comment by angelozerr** [comment]
> Am I correct in that it's like an informational message (like 'tern could not find any type at this position')?

Exactly!

> @angelozerr if it's not an error (a normal situation) it just should not being reported.

Yes it's my fix. I don't log this ren error in the log view. But I throw this error for displaying it in the tern console (used by developper). Is it OK?

Please try it and tell me if I can close this issue. Thanks!

**Comment by vrubezhny** [comment]
IMHO it is acceptable solution.

Thanks!

**Comment by angelozerr** [comment]
@vrubezhny can I close this issue?

**Comment by vrubezhny** [comment]
https://github.com/angelozerr/tern.java/commit/ca66921b9a0b0191bd121d525c74895f538fac65#commitcomment-15698531

Are you sure it will work for any system languages other than English?

**Comment by angelozerr** [comment]
> Are you sure it will work for any system languages other than English?

Yes it will work. Tern error message are hard coded. See https://github.com/angelozerr/tern.java/blob/master/core/ternjs/node_modules/tern/lib/tern.js#L841

I know it's not a clean mean, but I have none idea how to do that with clean mean.

**Comment by vrubezhny** [comment]
Then it should work.
Thanks!
