### ISSUE TITLE
tern-jshint ignore file open the editor still validate

### ISSUE THREAD

**Issue by HaiboLee** [angelozerr/tern.java#397]
@angelozerr I use the tern-jshint,  min.js file is configured to ignore the inspection,when i Validate the project it is OK, but I open the js file in the editor is still validate, Are specially designed so that? I think when the file is bigger, the validate is accounted for resources.
![test](https://cloud.githubusercontent.com/assets/16329338/12719365/8ebb19e4-c92f-11e5-834c-a2a48a795f4f.png)
When the file is bigger you click on the Red Cross on the side of the editor, often lead to eclipse no response.
![testb](https://cloud.githubusercontent.com/assets/16329338/12719370/92a90930-c92f-11e5-8df8-3e4088ccf391.png)

**Comment by HaiboLee** [comment]
oh,i know the problem .it's jsdt validator problem.when the file is bigger,it leads to high CPU for long time

**Comment by angelozerr** [comment]
Please post your issue to eclipse bugzilla JSDT.

I close this issue.
