### ISSUE TITLE
how to disable "synchronizing script resources with tern server" in eclipse.

### ISSUE THREAD

**Issue by Saurabh06** [angelozerr/tern.java#407]
how to disable "synchronizing script resources with tern server" in eclipse.

**Comment by angelozerr** [comment]
tern.java needs to synchronize script resources to send to the tern server the JS files to analyze. So you could disable this synch, ternjs will not work.

Why do you wish to disable the synchronization? I suppose because it's slow? If it that you must exclude folder (like node_modules) by using JSDT Include Path.

**Comment by Saurabh06** [comment]
Yes @angelozerr, I want to disable the sync of node modules with tern server because it takes lot of time for sync node modules and it start automatically after some interval for sync up. Actually i want to run protractor test cases from eclipse so for that i have installed AngularJS- 1.2.0 snapshot, which also installs the tern server. Is any requirement of tern server to run protractor test cases from eclipse.
And i have excluded node modules folder from JSDT Include path but still it sync up with tern server
![capture16](https://cloud.githubusercontent.com/assets/17181080/13312557/a42d289e-dbbd-11e5-9ffd-b85ab85af2ae.JPG)

**Comment by angelozerr** [comment]
Please try with ****/node_modules/***

**Comment by angelozerr** [comment]
@Saurabh06 is my suggestion resolves your problem?

**Comment by Saurabh06** [comment]
yes @angelozerr its get resolved, thanks

**Comment by serifeciftci** [comment]
Hi,

I'm working in a Java EE Web Project and have the same issue. Everytime I open a js/html file the popup pops up. 
I checked the JSTD Include Path which excluded the bower components, node modules and .min.js
Any suggestions?

**Comment by angelozerr** [comment]
> Any suggestions?

Please share your project.

**Comment by serifeciftci** [comment]
@angelozerr you can find the code [here](https://github.com/serifeciftci/repo1)

**Comment by angelozerr** [comment]
Thanks I have tried and I don't see the problem? You have few JS files, so it's quick, no?

Please explain me more what is your problem (which file you open, which problem you have, etc).

**Comment by serifeciftci** [comment]
![knipsel3](https://cloud.githubusercontent.com/assets/3762900/18784102/2091fc3e-8190-11e6-92cf-e5c33f42ce71.PNG)

Each time i click on a html/ js file this popup keeps popping up. The same happens on other projects so maybe the code isn't the problem

**Comment by angelozerr** [comment]
I have not this problem.

Which version of tern.java are you using?

I suggest you that you use Eclipse Jee Neon with tern.java 1.3.0-SNAPSHOT.

**Comment by serifeciftci** [comment]
I'm using Eclipse EE Mars. I don't know where to find or how to upgrade the Tern version.

**Comment by angelozerr** [comment]
Try with Eclipse Jee Neon and see https://github.com/angelozerr/tern.java/wiki/Installation-Update-Site

**Comment by iabdelrahman** [comment]
Windows > Preferences > Type Tern in the search >check the box next to disable
