### ISSUE TITLE
ESLint Comma-Dangle

### ISSUE THREAD

**Issue by Knight-Yoshi** [angelozerr/tern.java#408]
So ESLint with Tern is giving me an error for every object and array with a trailing comma and is also throwing errors for unused variables.
eslint.json
```
{
	"extends": "eslint:recommended",
	"root": true,
	"ecmaFeatures": {
		"blockBindings": true,
		"forOf": true,
		"jsx": true
	},
	"rules": {
		"arrow-spacing": [2, { "before": true, "after": true }],
		"comma-dangle": [2, "always-multiline"],
		"eqeqeq": [2, "allow-null"],
		"quotes": [2, "single"],
		"no-duplicate-case": 2,
		"no-empty-character-class": 2,
		"no-extra-parens": 2,
		"no-extra-semi": 2,
		"no-invalid-regexp": 2,
		"no-irregular-whitespace": 0,
		"no-negated-in-lhs": 2,
		"no-redeclare": 2,
		"no-sparse-arrays": 2,
		"no-this-before-super": 2,
		"no-unused-vars": 0,
		"no-use-before-define": 2,
		"semi": [2, "always"],
		"use-isnan": 2
	},
	"ecmaFeatures": {
		"regexYFlag": true,
		"regexUFlag": true
	},
	"env": {
		"es6": true,
		"browser": true,
		"jquery": true
	},
	"globals": {
		"jQuery": false,
		"chrome": false,
		"Foundation": false
	}
}

```

test.js
```
var arr = [
  'a',
  'b',
  /hello/,
];
```

However, when I use the CLI, `eslint -c eslint.json test.js`, it does't display said errors. I made sure it was validating correctly on the command line by changing comma-dangle to `[2, "never"]` then on the command line it had errors about trailing commas. I also tested other things, such as `use-isnan` and that also worked fine. So I'm not sure why commas are a problem.

**Comment by angelozerr** [comment]
Which version of tern.java do you use? Please test with 1.2.0

**Comment by Knight-Yoshi** [comment]
I _was_ on 1.1.0. Thanks for that though! That solved that. :D
I also can't seem to figure out why auto-complete is not working; going off of https://github.com/angelozerr/tern.java/wiki/Tern-Eclipse-IDE

**Comment by angelozerr** [comment]
@Knight-Yoshi you mean that tern completion doesn't work in 1.2.0?

At first I suggest you that you activate tern console with Properties / Tern / Developement/ trace on console.

Please share your project if you have troubles.

**Comment by Knight-Yoshi** [comment]
I couldn't get it to work in 1.1.0 either. 
I made a test repo with Tern configured the exact same way as my actual project.
https://github.com/Knight-Yoshi/terntest

**Comment by angelozerr** [comment]
Have you error in the Error Log view? Have you activated 'trace on console?"

**Comment by Knight-Yoshi** [comment]
Yeah, but it doesn't have an error message aside from what ESLint throws
```
-----------------------------------
Tern request#eslint: 
{"query":{"type":"eslint","fix":true,"lineNumber":false,"file":"test.js"},"files":[{"name":"test.js","text":"var arr = ['a','b'];\n\n// arr does not have auto-complete\narr. // should have added auto-complete suggestions, but didn't when this was typed\n","type":"full"}]}
141

Tern response#eslint with 10ms: 
{"messages":[{"message":"Parsing error: Unexpected end of input","severity":"error","from":140,"to":141,"lineNumber":5,"file":"test.js"}]}
-----------------------------------
```

**Comment by angelozerr** [comment]
And what about Tern request#completion ?

**Comment by Knight-Yoshi** [comment]
That didn't show up in the log
.

**Comment by angelozerr** [comment]
When you do Ctrl+Space, none logs are displayed? That's very strange? Is there some logs in the "Error log" view?

**Comment by Knight-Yoshi** [comment]
Using control + space (I'm on Mac) showed the auto-complete. - I initially tried command + space, since most hot keys involving Ctrl are mapped to the command/meta key - though that did what I thought, open the Mac spotlight, but also added an error
```
-----------------------------------
{"query":{"type":"definition","file":"test.js","end":77},"files":[]}
Tern request#definition: 

Tern response#definition with 1ms: 
{"highlight":[{"type":"Error","start":0,"end":0,"message":"No type found at the given position."}]}
-----------------------------------
```
Not sure what purpose it has, but thought I'd mention that since Mac already uses the meta + space combination.

**Comment by angelozerr** [comment]
Your problem is about JSDT and not Tern IDE. I don't know Mac, but I suggest you that completion opens as soon as you type '.'

To do that go at Window / Preferences/ JavaSCript / Editor / Content Assist and activate "Enable auto activation".

**Comment by Knight-Yoshi** [comment]
Sweet, thanks! Tern is making Eclipse more bearable for JS development.

**Comment by angelozerr** [comment]
> Tern is making Eclipse far more bearable for JS development.

Thanks!

For your information, JSDT Team is working hard to improve it (Grunt, Gulp, npm, bower support, etc) which will be available in June. 

I'm working too a new project https://github.com/angelozerr/typescript.java which is an Eclipse Plugin for TypeScript. And TypeScript guys are supporting simple JavaSCript too (Salsa) and it starts having the same features than ternjs.
