### ISSUE TITLE
Tern Eclipse Javascript Support in PHP Files

### ISSUE THREAD

**Issue by rrefsland** [angelozerr/tern.java#411]
Hi,
Is there a way to enable Tern javascript support for PHP files?  Namely autocomplete with Tern's JQuery module.  

Tern autocompletes fine with .html files (inside script block) and .js files.    

However, php files with script block do not autocomplete at all.  

Thanks.

**Comment by angelozerr** [comment]
If your PHP editor is based on JSDT for JavaScript, it should work, but never really tested. Which plugins do you use for PHP?

**Comment by rrefsland** [comment]
Thanks for the quick reply.  

I installed Zend Studio trial just now to test it.  Enabled JS support which installed Tern libraries.  Same results (Tern code hinting works in .js file, but not in .php file inside script tag).

**Comment by angelozerr** [comment]
@kisaloyan-raev could you help me please about this issue. Thanks!

**Comment by kaloyan-raev** [comment]
@angelozerr Sorry, I missed the previous comments.

@mniewrzal Can you help here?

**Comment by mniewrzal** [comment]
Hi,
it looks that CA is not working with combination PHP + HTML + JS (PDT/Zend Studio). Later I will take a look what is going on there.

**Comment by mniewrzal** [comment]
Turns out that in **tern.eclipse.ide.jsdt.ui**  proposal computer **tern.eclipse.ide.jsdt.ui.contentassist.TernContentAssistProcessor** needs additional content type **org.eclipse.php.core.phpsource**. I will prepare patch for this.

**Comment by angelozerr** [comment]
@rrefsland once https://opensagres.ci.cloudbees.com/job/tern.java/877/ will be finished, please try to install tern.java 1.2.0-SNAPSHOT https://github.com/angelozerr/tern.java/wiki/Installation-Update-Site

Thanks @mniewrzal for your job!

**Comment by rrefsland** [comment]
Excellent.....will do.  I'll try it out this weekend.

**Comment by rrefsland** [comment]
I installed the updates to 1.2.0.  It improved a little. 
 
Ex: In a PHP file.....Starting out with "$" will popup JQuery (that's an improvement).  But after the selector period "$()." no methods show.    

In a javascript file, $(). will display all available methods.

**Comment by angelozerr** [comment]
@rrefsland @kaloyan-raev have you an idea?

**Comment by kaloyan-raev** [comment]
@mniewrzal could you take at this one too?

**Comment by mniewrzal** [comment]
@rrefsland Can you try convert your project to javascript project? To do this select your project and from context menu choose **Configure -> Convert to Javascript Project**.  After that I have result like on attached image.

![screenshot from 2016-05-03 17-09-23](https://cloud.githubusercontent.com/assets/7313031/14987941/f2e5f960-1151-11e6-9b8e-c6a2403a450f.png)

**Comment by angelozerr** [comment]
That's strange, it should work without converting your project to JavaScript project.

**Comment by mniewrzal** [comment]
Problem is probably only with .php files. When I will be sure that this is a problem I will try to fix situation. Today I had only a moment to verify problem.

**Comment by rrefsland** [comment]
Hey Angelo/Michael,

Appreciate the assistance.  Think we got it figured out now.  Discovered the culprit below…. 

 

Created a new javascript project, and a new php project to test.  Both could see JQuery assist OK.  

 

However, I went back to my original project, and ran into the same problem.  No JQuery assist???  What is going on……

The problem is this added junk Eclipse adds to the default script tag.  It messes with Tern assist.  

<<script type="text/javascript">



</script>

 

EXAMPLES: 

Standard (clean) script tag, works OK.  



 

 

Script tag with junk disables Tern.



 

 

Script tag with “almost” all junk removed, also disables Tern.  This is what hung me up.    



 

Clean <script> tags work just fine.  

 

Randy

**Comment by angelozerr** [comment]
@rrefsland if I understand your problem, when you have`<!--` after `<script type="javascript" >`,, it breaks tern completion? If it that it's a bug with tern.java. To support completion tern.java extract JavaScript code from HTML with https://github.com/angelozerr/tern.java/blob/master/core/tern.core/src/tern/server/protocol/html/HtmlHelper.java#L50

It replaces HTML code with spaces and keep JS code and push this content to the tern server. I have not supported `<!--` and perhaps tern doesn't support that.

To fix the problem, https://github.com/angelozerr/tern.java/blob/master/core/tern.core/src/tern/server/protocol/html/HtmlHelper.java#L50 should be improved to replace  `<!--`  with spaces when it is after  `<script type="javascript" >`

Any contribution are welcome!

**Comment by rrefsland** [comment]
@angelozerr  
Thanks for the explanation.  It helped when I visited the link to extractJS().  The Tern library is so huge man.... 

Just to summarize:
Tern can handle `<!--  --!>` inside the script tags OK.  

Tern does not handle a script tag with two `<<`.  For example `<<script type="text/javascript">`.  I'm not sure why Eclipse adds a default script tag with two `<<`.  Who knows....Not a big deal.  

Anyhow, case closed!  I'll take a look and see if I can help.
