### ISSUE TITLE
angular tag, ng-app not recognized in Eclipse 4.5

### ISSUE THREAD

**Issue by datasmithtech** [angelozerr/tern.java#413]

**Comment by angelozerr** [comment]
It works for me with 1.2.0-SNAPSHOT, please share your project.

**Comment by datasmithtech** [comment]
Can you please refer me to a good sample?

Larry



Larry

**Comment by angelozerr** [comment]
It should work with any project. I suggest you that you install 1.2.0-SNAPSHOT https://github.com/angelozerr/tern.java/wiki/Installation-Update-Site

**Comment by datasmithtech** [comment]
Can I use the latest version of eclipse?

**Comment by angelozerr** [comment]
> Can I use the latest version of eclipse?

It works with Eclipse Mars. Not tested with Neon (which will be available in June)

**Comment by angelozerr** [comment]
@datasmithtech have you fixed your prblem? Please give me more info about your problem. More your issue is about AngularJS Eclipse and not tern.java

**Comment by angelozerr** [comment]
None answer, I close this issue.
