### ISSUE TITLE
JSHint validation does not use Script Paths

### ISSUE THREAD

**Issue by QualifiedSuccess** [angelozerr/tern.java#414]
Hi,

in my Project i want to validate all *.js files in my app/js folder. I set in my Eclipse Preferences under Tern->Script Paths that folder and it shows all my files. I configured JSHint as well and saved my settings. When validation starts i can see that every js file in my project gets validated instead of just the bunch of flies in my Script Paths.

How can i configure JSHint to only validate my files?

**Comment by angelozerr** [comment]
It was a bug. Please install tern.java 1.2.0-SNAPSHOT with [update site](https://github.com/angelozerr/tern.java/wiki/Installation-Update-Site) once https://opensagres.ci.cloudbees.com/job/tern.java/876/ will be finished.

**Comment by QualifiedSuccess** [comment]
Thanks, that works.
