### ISSUE TITLE
How to use my made eslint.json file for validation instead of default eslint.json file using eclipse

### ISSUE THREAD

**Issue by Saurabh06** [angelozerr/tern.java#417]
I want to use my made eslint config file instead of default eslint file for javascript validation in my tern protractor project. Can you please help me out how to use my config file instead of default eslint in eclipse for validation.

**Comment by angelozerr** [comment]
https://github.com/angelozerr/tern.java/wiki/Tern-Linter-ESLint#configfile should help you

**Comment by Saurabh06** [comment]
Thanks, @angelozerr 
And can you help me out how to export all error generated through eslint during validation in eclipse in some file

**Comment by angelozerr** [comment]
> And can you help me out how to export all error generated through eslint during validation in eclipse in some file

The only trace that you could have is that you enable Tern Console (see Tern / Developement) project properties, but you will hav etrace too for completion, hover etc.

Perhaps you should execute eslint with line command to hav eonly eslint errors.

**Comment by Saurabh06** [comment]
@angelozerr how to do with command line??
Can you help me for setup and installation of eslint for validate my javascript project.

**Comment by angelozerr** [comment]
> how to do with command line??

http://eslint.org/docs/user-guide/command-line-interface

> Can you help me for setup and installation of eslint for validate my javascript project.

It's out teh scope of tern.java, I have no time to help you for that, please read the eslint doc http://eslint.org/docs/user-guide/command-line-interface
