### ISSUE TITLE
Mark occurrences is often completely wrong

### ISSUE THREAD

**Issue by acarstoiu** [angelozerr/tern.java#422]
It may be that it's not _tern_ that provides this functionality, but JSDT. No surprise here, but can you intercept the triggering events and make it properly? It is the local only (file) version of #339.

Thanks.

**Comment by angelozerr** [comment]
tern.java doesn't support mark occurrences and it will not. It's the goal of JSDT. JSDT 2.0 (Eclipse Neon) which is sonn available is a lot improve.

I close this issue.

**Comment by acarstoiu** [comment]
Well, I'm reporting this while running on Neon RC (JSDT _2.0.0_).

**Comment by angelozerr** [comment]
@acarstoiu I have seen some bugs about mark occurrences inside JSDT bugzilla. I suggeset you that you post your bug in the JSDT bugzilla.

JSDT Editor doesn't give the capability to override mark occurences, so it's not possible to do it with tern. I have no time to support that, but any contribution are welcome.

**Comment by acarstoiu** [comment]
If marking occurences is not override-able, then I guess the guys developing JSDT have reserved this issue for themselves. If only they used a proper parser...

**Comment by angelozerr** [comment]
JSDT 2.0.0 uses Esprima parser, but there is discussion to use Google closure.
