### ISSUE TITLE
Validator errors are not showing up in the Problems view

### ISSUE THREAD

**Issue by acarstoiu** [angelozerr/tern.java#425]
I'm using the _JSHint_ validator and noticed that the validation errors do not show up in the **_Problems_** or **_Markers_** view. Related to that, they are not marked with a special decoration on the file's name (editor tab, file tree item).
The wrong outcome of this is that the developer does not have an overview of errored files and the IDE does not warn the user when attempting to commit :-1: 

I deem this lack of integration with the Eclipse error markers quite serious. If that helps, I'm willing to accept the validation to take place only upon saving (maybe through a configuration setting).

**Comment by angelozerr** [comment]
Please read https://github.com/angelozerr/tern.java/wiki/Tern-Linter#wtp-tern-validator

**Comment by acarstoiu** [comment]
I have configured the project as depicted in the last image of the page linked above, that is, I have the _Validator_ builder enabled for the project and the _Tern Validator_ is listed among the enabled validators.
The project has been rebuilt with and without the _JavaScript Validator_ also enabled as builder.

Still, with the currently edited file full of JSHint red markings, the file's icon is not decorated with an error pictogram and the **_Markers_** view does not mention it. I'm using:
- JavaScript Development Tools 2.0.0.v201605311817
- Eclipse Platform 4.6.0.I20160606-1100
- Tern JSDT feature	1.1.0.201511082254
- Tern Linters 1.1.0.201511082254
- Tern server node.js feature 1.1.0.201511082254

(not using "Tern feature" :warning:  )

**Comment by angelozerr** [comment]
Please try with Eclipse JEE Neon + tern.java 1.2.0 SNAPSHOT https://github.com/angelozerr/tern.java/wiki/New-and-Noteworthy-1.2.0

**Comment by acarstoiu** [comment]
Sorry, there's something I don't get: how was _1.2.0_ released in 2015 long before _1.1.0_?

**Comment by angelozerr** [comment]
It was a mistake in teh wiki, I have fixed it.

**Comment by acarstoiu** [comment]
The dates are still wrong.

**Comment by angelozerr** [comment]
Fixed.
