### ISSUE TITLE
How do I install a new JSON file for my API into an already installed module?

### ISSUE THREAD

**Issue by shehrozhussain** [angelozerr/tern.java#428]
So, in my environment, a module which is a ZIP file is already loaded. Now, later on, I get an updated JSON with new API information from somewhere. How do I install the new JSON to replace the old one in the module that was already loaded?

What public API calls can I use?

**Comment by angelozerr** [comment]
I'm not sur to understand what you wish, but perhaps https://github.com/angelozerr/tern.java/wiki/Tern-IDE-Extension#ternmoduleinstalls is what you are searching.

**Comment by shehrozhussain** [comment]
I already have created a module for tern to consume. The module provides the API definition in JSON format. The module is currently a .zip folder with the name tern-mystuff. It has a JSON file with the API called mystuff.json. 

Now, during the installation, the module gets installed. What I want to do is update the API provided by a new JSON file when an updated API becomes available (basically, I want to dynamically update the API provided by the JSON file) by replacing the old mystuff.json with a new version of mystuff.json.

**Comment by angelozerr** [comment]
> basically, I want to dynamically update the API provided by the JSON file

I don't understand what you expect about tern.java? Which feature do you need? An new extension point? Perhaps it's the same issue than https://github.com/angelozerr/tern.java/issues/323 ?

**Comment by shehrozhussain** [comment]
Ok, so the issue 323 is somewhat different. Basically what I want to ask: is there any way to update the JSON type definition once the tern plugin is already loaded? How to re-load it?

I believe this functionality is not available (from my understanding), if it is, then kindly point me to the right direction.
