### ISSUE TITLE
Extension point to specify Node.js installation location

### ISSUE THREAD

**Issue by sosahvictor** [angelozerr/tern.java#434]
I've noticed that Tern.java has this extension point[1] to specify a current node.js install location so that is taken automatically when Tern preferences are initialized. However, looking at the code that reads that extension[2] I can tell that it only looks for a directory under the plugin declaring the extension point, i.e. is relative to the plugin, or else it looks for a ZIP archive in the bundle.

In my scenario, I already have a node.js installed in a different location that I know in advance.

My question, is there a way to add node.js locations in Tern.java preferences either programatically or declaratively?

[1] https://github.com/angelozerr/tern.java/blob/master/eclipse/tern.eclipse.ide.server.nodejs.core/schema/nodeJSInstalls.exsd 
[2] https://github.com/angelozerr/tern.java/blob/master/eclipse/tern.eclipse.ide.server.nodejs.core/src/tern/eclipse/ide/server/nodejs/internal/core/NodejsInstall.java

**Comment by angelozerr** [comment]
> My question, is there a way to add node.js locations in Tern.java preferences either programatically or declaratively?

No.

The extension point could be improved to specifiy a class to return a custom file node path.

**Comment by sosahvictor** [comment]
> No.
> 
> The extension point could be improved to specifiy a class to return a custom file node path.

Thanks for confirming Angelo. Will think about this. As we require this functionality, we'll be contributing a patch soon.

Quick question, talking about release timeline, do you plan to release something within the next two months? This can help to plan my work.

Thanks again.

**Comment by angelozerr** [comment]
> Quick question, talking about release timeline, do you plan to release something within the next two months? This can help to plan my work.

To be honnest with you, I don't know when tern.java will be released. We do a release when there are interesting features. But SNAPSHOT version is available as soon as pushes are done.

**Comment by sosahvictor** [comment]
Alright. That should be enough. I'll be in touch soon about this contribution.
Thank you, Angelo!

**Comment by angelozerr** [comment]
> I'll be in touch soon about this contribution.

Cool:)

> Thank you, Angelo!

You are welcome!

**Comment by sosahvictor** [comment]
Hi @angelozerr.
I've created PR https://github.com/angelozerr/tern.java/pull/435. I guess it's better to track it there. If you have the same feeling, please feel free to close this one

**Comment by angelozerr** [comment]
Thanks @sosahvictor!

Please read my comment https://github.com/angelozerr/tern.java/pull/435/files#r73936067

I close this issue.

**Comment by sosahvictor** [comment]
oh, btw, where can I find the snapshot that has this change?

**Comment by angelozerr** [comment]
You can install SNAPSHOT version with update site https://github.com/angelozerr/tern.java/wiki/Installation-Update-Site

You work is included in this snapshot, see https://opensagres.ci.cloudbees.com/job/tern.java/

**Comment by sosahvictor** [comment]
Thanks for the pointers
