### ISSUE TITLE
No support for adding project root to Script Paths

### ISSUE THREAD

**Issue by cloudyafternoon** [angelozerr/tern.java#437]
In Eclipse Neon, when I try to add the project root to the Script Paths, this is ignored.

![2016-09-08_15-27-58](https://cloud.githubusercontent.com/assets/21170969/18351103/17895f6e-75d9-11e6-866c-792020b90daf.png)

After clicking "OK", the new path is not added. In addition, I cannot remove the "WebContent" folder.

![2016-09-08_15-30-29](https://cloud.githubusercontent.com/assets/21170969/18351150/4da0f5f8-75d9-11e6-82b5-0b7321e6341d.png)

**Comment by angelozerr** [comment]
Your script path comes from JSDT (Include Path), that's why you cannot remove it. Please use Include Path which gives the capability to include/exclude paths.

**Comment by angelozerr** [comment]
None answer, I close this issue.

**Comment by cloudyafternoon** [comment]
Thank you. I managed to exclude folders jusing the JSDT include path.
