### ISSUE TITLE
Tern IDE not working with Spring's STS

### ISSUE THREAD

**Issue by jbhardwaj12** [angelozerr/tern.java#451]
I am trying to use Tern IDE and tooling with Spring Tool Suite, which is eclipse based platform. It seems to have been installed fine. But I can not see Configuration options under project properties not I do see anything related to Tern under Windows Preferences. Is there a compatibility issue with STS ?

![image](https://cloud.githubusercontent.com/assets/11051205/23437249/0216b5fa-fdd3-11e6-8247-bb25e8d6211e.png)

Its a springboot project and I am trying to add Tern IDE for angular JS part.

**Comment by angelozerr** [comment]
Have you done that https://github.com/angelozerr/tern.java/wiki/Getting-Started#tern-configuration

If this menu doesn't appears, perhaps your project is allready a tern project (it contains the .tern-project file in the roor of your project)?

**Comment by jbhardwaj12** [comment]
@angelozerr Sorry, I think I was on clear and tried to sum that under one line 
`But I can not see Configuration options under project properties not I do see anything related to Tern under Windows Preferences.`
Please see elaborated issue below :
I installed tern via Eclipse Marketplace, I can see it installed under installation details. I also tried to manually add via update site - It shows latest  version already installed there too.

1.  There is no .tern-project file, I would expect it to appear post configuration.  I do not see option to configure as described as Tern Configuration. https://github.com/angelozerr/tern.java/wiki/Getting-Started#tern-configuration
2. I do not see Tern under preferenes section as described in Preferences Settings https://github.com/angelozerr/tern.java/wiki/Getting-Started#preferences-settings

I have restarted STS a few times but no luck.

**Comment by angelozerr** [comment]
Do you use project explorer? Please add scrennshot with your contextual menu.

Try to create at hand a .tern-project file and fill it with `{}`

Open project properties and try to type tern in the filter (or search Tern or JavaScript / Tern) properties page

**Comment by jbhardwaj12** [comment]
@angelozerr  Thank you for your time on this. This is not a tern issue. 

I tested on Vanilla STS bundle and tern is working as expected there.  Looks like there is some conflict between plugins in STS installation I was using earlier.  I am closing this issue.
