### ISSUE TITLE
Unable to install with eclipse neon.3

### ISSUE THREAD

**Issue by htreu** [angelozerr/tern.java#452]
I tried both, marketplace URL and update site (1.3.0-SNAPSHOT) and have the same results with both methods:
- the tern packages/bundles are listed in the "Installed Software" tab (see screenshot),
- the tern plugin is not showing up in the "Plug-Ins" tab,
- the "Convert to Tern Project" entry is missing in the project context menu,
- the Tern entry in the Preferences menu is missing.

What can I do to track down the issue? The OSGi console in eclipse does not show any tern related bundles, services or packages.

<img width="768" alt="screen shot 2017-05-02 at 16 17 42" src="https://cloud.githubusercontent.com/assets/1729268/25621995/5b64f1c4-2f53-11e7-86f2-f35a8e09f515.png">
<img width="768" alt="screen shot 2017-05-02 at 16 17 53" src="https://cloud.githubusercontent.com/assets/1729268/25621997/5e57b29a-2f53-11e7-95ca-613350221014.png">

Thanks.

**Comment by neilrackett** [comment]
I'm seeing the same issue on Neon 3 for Windows (and also with the AngularJS and Angular2 plugins)

**Comment by angelozerr** [comment]
Have you tried with a fresh Eclipse Neon3? It works for me.

>  Angular2 plugins

If you mean https://github.com/angelozerr/angular2-eclipse there is no Convert menu, if you have some trouble with Angular2 Eclipse please create an issue.

**Comment by zhenizhui** [comment]
same, too.
```
win 10
neon.3
```

**Comment by neilrackett** [comment]
I wasn't able to install on neon.3, even a fresh install, but it appears to be working without any problems after upgrading to Oxygen.

**Comment by krkhnh** [comment]
I'm using Oxygen and having the same issue after updating to 1.2.0.201711281852. Works well with 1.2.0.201606160856. So I'm not updating Tern for now.

**Comment by htreu** [comment]
I'm updated to Oxygen and Tern IDE in Version 1.2.0.201606160856 (from the Marketplace) works well now.
Thanks.
