### ISSUE TITLE
Support for navigator.getUserMedia

### ISSUE THREAD

**Issue by mplescano** [angelozerr/tern.java#460]
Guys:

I think it's necessary to add support for : 
navigator.getUserMedia, 
navigator.webkitGetUserMedia, 
navigator.mozGetUserMedia, 
navigator.msGetUserMedia

besides:
video.src
video.onloadedmetadata

Regards

**Comment by angelozerr** [comment]
I suggest you that you do a PR for that in https://github.com/ternjs/tern/pulls
