### ISSUE TITLE
tern of eclipse not dose work that calculating completion proposals…

### ISSUE THREAD

**Issue by doldoldol21** [angelozerr/tern.java#475]
consol : 

Nodejs Commnand: "D:\JSP작업\.metadata\.plugins\tern.eclipse.ide.server.nodejs.embed.win32.win32.x86_64\node-v4.2.4-win32-x86_64\node.exe" "C:\Users\rdi\.p2\pool\plugins\ternjs_1.2.1.201611022209\node_modules\tern\bin\tern" --no-port-file --disable-loading-local
.tern-project: {
  "ecmaVersion": 6,
  "plugins": {
    "guess-types": {
      
    },
    "outline": {
      
    },
    "es_modules": {
      
    },
    "browser-extension": {
      
    },
    "jquery-extension": {
      
    }
  },
  "libs": [
    "browser",
    "jquery"
  ]
}
Project dir: D:\JSP작업\P

never ending 'calculating completion proposals…' process bar

Can you solve this?

I'm sorry that my English grammar is wrong.

**Comment by angelozerr** [comment]
I gave up the project.  I suggest that you install https://github.com/eclipse/wildwebdeveloper

**Comment by doldoldol21** [comment]
Thanks for the answer, I hope it's full of good things
