### ISSUE TITLE
Parse JS file of tern doc with monitor

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/tern.java#5]
Parse JS file of tern doc with monitor

**Comment by angelozerr** [comment]
Done with async tern completion https://github.com/angelozerr/tern.java/wiki/New-and-Noteworthy-0.9.0#async-tern-completion

**Comment by paulvi** [comment]
Is it possible just to add more options into list when they arrive?

or make first line selection as "Retry" command

**Comment by angelozerr** [comment]
> Is it possible just to add more options into list when they arrive?

Asyn tern completion is done every time. When tern server starts quicly (not a lot of JS files), the completion shows the result directly otherwise it shows in the completion that tern server is working.

I'm not sure that it was your question?

**Comment by paulvi** [comment]
I just seen implementations where suggestion list content grows (user sees more options as they are added). So user does not need to press anything, just wait. When the full option list is shown above line "Processing..." disappears.

It is just other user experience.

**Comment by piotrtomiak** [comment]
Was it eclipse? If so, looking at how it was done would be very interesting and I guess we could apply similar solution to tern.java.

**Comment by paulvi** [comment]
That IntelliJ-based Android Studio giving suggestions inside Java class.
Java inside IntelliJ IDEA CE is open source, but I won't think it is worth looking at.

BTW with Android API it is quite common to have data in a List that is displayed in Adapter, then underlying data is updated and UI elements are notified to be updated. Isn't it so with Eclipse APIs?

**Comment by angelozerr** [comment]
> Was it eclipse? If so, looking at how it was done would be very interesting and I guess we could apply similar solution to tern.java.

Today it seems that "asynchronous ContentAssist" is not possible with Eclipse. I have created an issue at https://bugs.eclipse.org/bugs/show_bug.cgi?id=463210

**Comment by paulvi** [comment]
yep, closed as duplicate of old [Bug 251156 - [content assist] Asynchronous code completion](https://bugs.eclipse.org/bugs/show_bug.cgi?id=251156)
